### ISSUE TITLE
Improve error handling on incorrect API calls

### ISSUE THREAD

**Issue by yannickstruyf3** [nutanix/terraform-provider-nutanix#112]
When performing 'incorrect' API calls via the terraform provider, the "status" field on the API is being set to "error". Trying to shrink disks will cause this state.

 This state makes it impossible to use Terraform afterwards. 

The only way of getting the VM out of error state is the following:
 - Retrieve the UUID of the virtual machine (should be in your statefile)
 - Perform a GET  request on https://<< Prism IP >>:9440/api/nutanix/v3/vms/<< VM UUID >>
 - Take the output, remove the “status” key from the JSON
 - Perform a PUT request using the retrieved payload on https://<< Prism IP >>:9440/api/nutanix/v3/vms/<< VM UUID >>

Improving error handling should resolve this issue.

**Comment by PacoDw** [comment]
Could you share the configuration or the steps to recreate the issue?

**Comment by yannickstruyf3** [comment]
To force this error you can perform following steps:
First create a vm:
```
resource "nutanix_virtual_machine" "vm" {
  name                  = "mytest"
  cluster_uuid          = "my-cluster-uuid"
  num_vcpus_per_socket  = "1"
  num_sockets           = "2"
  memory_size_mib       = 2048
  power_state_mechanism = "ACPI"

  disk_list {
    disk_size_bytes = 40 * 1024 * 1024 * 1024
  }
}
```
After creation, shrink the disk (not supported):
```
resource "nutanix_virtual_machine" "vm" {
resource "nutanix_virtual_machine" "vm" {
  name                  = "mytest"
  cluster_uuid          = "my-cluster-uuid"
  num_vcpus_per_socket  = "1"
  num_sockets           = "2"
  memory_size_mib       = 2048
  power_state_mechanism = "ACPI"

  disk_list {
    disk_size_bytes = 20 * 1024 * 1024 * 1024
  }
}
```

Will result in failures of the next plan, apply, destroy:
`Error: error waiting for vm (vmid) to update: error_detail: INVALID_ARGUMENT: NotSupported: Can't shrink disk at scsi.0 of VM vmid., progress_message: update_vm`

The only way to resolve this situation is by performing the manual steps listed in the issue or deleting the VM via the UI.
