### ISSUE TITLE
Error on applied Resource

### ISSUE THREAD

**Issue by rhizoet** [nutanix/terraform-provider-nutanix#113]
If I build a new VM with Terraform 0.12.24 (latest), no matter if with the provider in version 1.0.2 or upstream, I can't do any further provisioning on the same VM afterwards. The purpose of Terraform will then cease to exist.

I get the following error message:

`Error: error: {
  "api_version": "3.1",
  "code": 400,
  "kind": "vm",
  "message_list": [
    {
      "message": "Request could not be processed.",
      "reason": "INVALID_REQUEST"
    }
  ],
  "state": "ERROR"
}`

That's all I get about this error.

Why do I get such an error message? Is the PC version too new or are there other dependencies?

**Comment by PacoDw** [comment]
Hello @rhizoet could you share your Terraform configuration to be able to recreate the issue omitting sensitive data?

**Comment by yannickstruyf3** [comment]
@rhizoet did this issue also occur in the latest version of the Nutanix provider? If not we will close this case.

**Comment by abhimutant** [comment]
Closing this issue as it has been open for 2 years and no response from the issuer.
