### ISSUE TITLE
Feature requests: max length for metadata / userdata in guest customization

### ISSUE THREAD

**Issue by htj** [nutanix/terraform-provider-nutanix#115]
Hi

The metadata/userdata fields in guest customization are often very long. This makes the output of apply quite large. Often multiple pages in what is already a big terminal (50x140), and it isn't really helpful. In fact it makes it harder to see what is happening. Often the data can also contain secrets, which one would prefer not to have shown on the terminal.

Only showing the first 30 characters (or something under 100) followed by ... would be good.

Not sure if this is possible in terraform, but it would be nice.

**Comment by Crizstian** [comment]
This is no issue, i have tested on the branch develop and it didnt prompt an error, it creates de vm correctly, closing this issue this is related to #119

**Comment by htj** [comment]
I agree this is not a feature as such, and that it works correctly right now.

This is an ergonomics / quality of life suggestion. It doesn't sound like that was well communicated.
