### ISSUE TITLE
Terraform wants to change VMs bootstrapped with cloud init

### ISSUE THREAD

**Issue by htj** [nutanix/terraform-provider-nutanix#122]
Hi

This is a rather... interesting behaviour:

First I create two VMs with cloud init guest data with terraform. Stuff works.

After the two VMs, have been started, and I run terraform apply again, I get this:

```
htj@iridium:~/projects/ndn-iaas/tfntnx$ terraform apply
nutanix_subnet.vlan66: Refreshing state... (ID: 409dfe87-8c94-469b-ae6a-23f457ae586f)
nutanix_subnet.vlan67: Refreshing state... (ID: 5a3253fc-dec0-4fdd-b9a4-b532358ac2e6)
nutanix_virtual_machine.terraform-test-se-tug-ntp01_nordu_net: Refreshing state... (ID: 3fcef6dd-3e6f-490b-b9d6-6e3c8ffd8bd0)
nutanix_virtual_machine.terraform-test-niab: Refreshing state... (ID: 6c710de8-5b33-4f01-bbde-cac69f2cd303)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ nutanix_virtual_machine.terraform-test-niab
      disk_list.#:                                 "2" => "1"
      disk_list.0.data_source_reference.0.kind:    "" => "image"
      disk_list.0.data_source_reference.0.name:    "" => "ubuntu-16.04-server-cloudimg-amd64-disk1-20180509-console-fix.img"
      disk_list.0.data_source_reference.0.uuid:    "" => "058e0f7c-a294-4730-a355-0326f6127898"
      disk_list.0.device_properties.0.device_type: "CDROM" => "DISK"
      disk_list.0.disk_size_mib:                   "1" => "10000"
      guest_customization_cloud_init.%:            "2" => "1"
      guest_customization_cloud_init.meta_data:    "" => ""
      nic_list.0.subnet_reference.%:               "3" => "2"
      nic_list.0.subnet_reference.name:            "VM-vlan-66" => ""
      nic_list.1.subnet_reference.%:               "3" => "2"
      nic_list.1.subnet_reference.name:            "vlan67-Freerange" => ""

  ~ nutanix_virtual_machine.terraform-test-se-tug-ntp01_nordu_net
      disk_list.#:                                 "2" => "1"
      disk_list.0.data_source_reference.0.kind:    "" => "image"
      disk_list.0.data_source_reference.0.name:    "" => "ubuntu-16.04-server-cloudimg-amd64-disk1-20180509-console-fix.img"
      disk_list.0.data_source_reference.0.uuid:    "" => "058e0f7c-a294-4730-a355-0326f6127898"
      disk_list.0.device_properties.0.device_type: "CDROM" => "DISK"
      disk_list.0.disk_size_mib:                   "1" => "10000"
      guest_customization_cloud_init.%:            "2" => "1"
      guest_customization_cloud_init.meta_data:    "" => ""
      nic_list.0.subnet_reference.%:               "3" => "2"
      nic_list.0.subnet_reference.name:            "vlan67-Freerange" => ""


Plan: 0 to add, 2 to change, 0 to destroy.
```

I haven't changed anything in the terraform files.

What I think happens, is that nutanix creates a small iso with the cloud init data, and attaches it to the VM (actually I'm pretty sure that is what happens). After the VM has been booted, the iso is detached from the VM, which changes the disk list. Terraform doesn't like this.

Doing the operations causes some error with not being able to change the ide bus device, but that is to be expected. There should not be an attempt of fixing it, as there is nothing wrong.

I'm not sure how to go about fixing this. First of all, I'm rather surprised that nutanix makes the cloud init iso the first device, instead of appending it to the list. Perhaps the cloud init iso shouldn't be exposed at all (but it obviously is). Maybe terraform shouldn't add the cloud init iso during creation (slightly tricky).

**Comment by JonKohler** [comment]
Terraform isn't doing anything with the cloud init ISO, but rather just telling the API to go "do something" related to cloud init, then the API does it under the covers. 

@Crizstian - can we work around this in the short term?

**Comment by htj** [comment]
Yeah, this doesn't quite fit the terraform model.

I think a potential work-around is to do the following when reading the response after vm creation:

if (cloudinit-stuff-defined)
  remove the cloud-init cdrom disk

This should make the disk schema fit with what is later read. I'll be happy to test this out if you make a branch for it first.


if (cloudinit stuff is

**Comment by JonKohler** [comment]
i think thats sane. We'll see what we can do! Thanks again @htj for being the trailblazer for our project here, we really appreciate it!

**Comment by Crizstian** [comment]
@htj @JonKohler I found out that when we use cloud_init values we can avoid using an image resource, because the cloud_init already provides an image, the problem the I still have is for updating a vm, but im still don't know if is an API error or is a provider error.

**Comment by htj** [comment]
Hi again
I'm not sure what is going with the networking, but it is consistent. Here is where I do a second terraform apply right after a VM creation:

```
htj@iridium:~/projects/ndn-iaas/tfntnx$ terraform apply
nutanix_subnet.vlan66: Refreshing state... (ID: 409dfe87-8c94-469b-ae6a-23f457ae586f)
nutanix_subnet.vlan67: Refreshing state... (ID: 5a3253fc-dec0-4fdd-b9a4-b532358ac2e6)
nutanix_virtual_machine.terraform-test-se-tug-ntp01_nordu_net: Refreshing state... (ID: e1c0ffdb-95b8-4502-84fd-373c67a870b5)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ nutanix_virtual_machine.terraform-test-se-tug-ntp01_nordu_net
      disk_list.#:                              "2" => "1"
      disk_list.0.data_source_reference.0.kind: "" => "image"
      disk_list.0.data_source_reference.0.name: "" => "ubuntu-16.04-server-cloudimg-amd64-disk1-20180509-console-fix.img"
      disk_list.0.data_source_reference.0.uuid: "" => "058e0f7c-a294-4730-a355-0326f6127898"
      guest_customization_cloud_init.%:         "2" => "1"
      guest_customization_cloud_init.meta_data: "" => ""
      nic_list.0.subnet_reference.%:            "3" => "2"
      nic_list.0.subnet_reference.name:         "VM-vlan-66" => ""
      nic_list.1.subnet_reference.%:            "3" => "2"
      nic_list.1.subnet_reference.name:         "vlan67-Freerange" => ""

```

The VM is created with two nics: First is an internal boot network, and other is external interface (configured with puppet). Ideally I'd just like one, but the nutanix cloud-init solution doesn't make it possible to specify IP addresses via cloud-init (very long explanation).

During boot, the first interface is configured with dhcp. Later on the second interface is brought up and configured with puppet (installed and started via cloud-init). The first interface is then shut down. Having the reference change is pretty weird, and I'm not sure what is going on.

Also the meta_data changing from "" to "' seems like a bug, but I'm not sure.

**Comment by htj** [comment]
Hi, I was looking a bit more into this. I dumped the spec of a VM right after creation, and then again after our automation had run. The specs in themselves are not very interesting, but diff shows at least one of the issues:

```
htj@iridium:~/projects/ndn-iaas/tfntnx$ diff -urN vm_spec_r0 vm_spec_r1
--- vm_spec_r0	2018-06-12 10:07:42.000000000 +0200
+++ vm_spec_r1	2018-06-12 10:09:06.000000000 +0200
@@ -6,7 +6,7 @@
               'project_reference': {'kind': 'project',
                                     'name': 'default',
                                     'uuid': 'f4610077-d442-4376-807b-5da7ff33bb46'},
-              'spec_version': 0,
+              'spec_version': 1,
               'uuid': 'c2ed91d4-416b-4ba8-8f89-97e3b433a02a'},
  'spec': {'cluster_reference': {'kind': 'cluster',
                                 'name': 'KAS-LAB-NTNX-1',
@@ -49,7 +49,7 @@
                                       'uuid': '7c19db42-19a0-4505-b1f3-a4881091b583'}],
                         'num_sockets': 1,
                         'num_vcpus_per_socket': 1,
-                        'power_state': 'OFF',
+                        'power_state': 'ON',
                         'power_state_mechanism': {'guest_transition_config': {'enable_script_exec': False,
                                                                               'should_fail_on_script_failure': False},
                                                   'mechanism': 'HARD'},
@@ -81,7 +81,9 @@
                           'hardware_clock_timezone': 'UTC',
                           'memory_size_mib': 512,
                           'nic_list': [{'ip_endpoint_list': [{'ip': '192.168.34.77',
-                                                              'type': 'ASSIGNED'}],
+                                                              'type': 'ASSIGNED'},
+                                                             {'ip': '192.168.34.77',
+                                                              'type': 'LEARNED'}],
                                         'mac_address': '50:6b:8d:ca:be:e0',
                                         'nic_type': 'NORMAL_NIC',
                                         'subnet_reference': {'kind': 'subnet',
@@ -97,11 +99,10 @@
                                         'uuid': '7c19db42-19a0-4505-b1f3-a4881091b583'}],
                           'num_sockets': 1,
                           'num_vcpus_per_socket': 1,
-                          'power_state': 'OFF',
+                          'power_state': 'ON',
                           'power_state_mechanism': {'guest_transition_config': {'enable_script_exec': False,
                                                                                 'should_fail_on_script_failure': False},
                                                     'mechanism': 'HARD'},
                           'vga_console_enabled': True,
                           'vnuma_config': {'num_vnuma_nodes': 0}},
-            'state': 'RUNNING'}}
-
+            'state': 'COMPLETE'}}
```

So, IP addresses of the first nic goes from:

```
                          'nic_list': [{'ip_endpoint_list': [{'ip': '192.168.34.77',
                                                              'type': 'ASSIGNED'}],
                                        'mac_address': '50:6b:8d:ca:be:e0',
```
to
```
                          'nic_list': [{'ip_endpoint_list': [{'ip': '192.168.34.77',
                                                              'type': 'ASSIGNED'},
                                                             {'ip': '192.168.34.77',
                                                              'type': 'LEARNED'}],
                                        'mac_address': '50:6b:8d:ca:be:e0',
```
I consider this be a rather small changed, but not something that should trigger an apply. Going from assigned to learned should be considered normal.

Looking at this it is clear that the current code operate per ip address and not per interface. It is very much possible for an interface to have multiple IPs, but this should not trigger a reorganization of the nic list. It could be considered to remove the LEARNED entry, however this will not be enough - the code needs to be interface centric, not IP centric.

Looking at the first VM spec returned, the cloud init cdrom is present there, and I wouldn't be suprised if it was included in the VM creation return. However what gets written to the terraform state is probably what you send, not what was returned from the nutanix API. One could argue that an intend based API shouldn't change the spec, but I'm not sure that is possible or a good idea. If possible, the terraform state should be what was returned by the creation, not what was send to terraform.

**Comment by JonKohler** [comment]
@Crizstian - does this give you enough to go on?

**Comment by Crizstian** [comment]
Havent had the chance to review it, let me work on it and i will tell you

**Comment by marinsalinas** [comment]
@JonKohler, @htj   we've made two scenarios one with cloud_init and another one without it, in the scenario where don't include cloud_init and we perform an update everything works OK, but where the configuration has the cloud_init it fails.

Here is the error message:

```"message_list": [
    {
      "message": "error_code: 17\nerror_detail: \"Cannot complete request in state InvalidState: Cannot complete request in state On\"",
      "reason": "INTERNAL_ERROR"
    }
  ],
  "state": "ERROR"
}```

Maybe when the cloud_init is in the configuration we cannot perform an update.

**Comment by htj** [comment]
Hi

I've been able to make an update with cloud-init so it should be possible.

I've gotten the above message as well, but cannot remember for what. It might be that you have metadata specified. Basically you shouldn't bother with metadata, as you cannot really do anything useful with it on nutanix.

**Comment by htj** [comment]
Oh, and you should definitely not change any of cloud init values.

**Comment by JonKohler** [comment]
@htj - can you retry this with the RC1 code that is posted under releases?

**Comment by htj** [comment]
Hi

Sorry for the long reply, but I think getting the details right is important :-).

Short version: It seems to be working now

I had to adjust the field name for cloud_init and remove name under disk. This is probably intentional.

I create a vm as usual, and on the second apply, I got this:

```
htj@iridium:~/projects/ndn-iaas/tfntnx$ terraform apply
nutanix_subnet.vlan66: Refreshing state... (ID: 409dfe87-8c94-469b-ae6a-23f457ae586f)
nutanix_subnet.vlan67: Refreshing state... (ID: 5a3253fc-dec0-4fdd-b9a4-b532358ac2e6)
nutanix_virtual_machine.terraform-test-se-tug-ntp01_nordu_net: Refreshing state... (ID: 5ec3828f-0a3b-4be2-92f8-463494ec5f74)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ nutanix_virtual_machine.terraform-test-se-tug-ntp01_nordu_net
      disk_list.0.disk_size_mib: "2252" => "10000"


Plan: 0 to add, 1 to change, 0 to destroy.
```

Terraform wants to change the size of the disk. This is due to me specifying disk size AND using an image. In this case AHV will ignore the disk size, and just clone from the image. I currently have a case for this at Nutanix, issue number: 00340671 . From VMWare we are used to this doing a clone and then disk resize, which is quite handy. I'm not sure if this something you guys want to account for, but I'm mentioning it here for completeness. We've worked around this issue by resizing the image manually before uploading.

For fun, I tried doing the request, but it failed:

```
* nutanix_virtual_machine.terraform-test-se-tug-ntp01_nordu_net: error: {
  "api_version": "3.1",
  "code": 422,
  "message_list": [
    {
      "details": {
        "spec.resources.disk_list.0.device_properties.disk_address.device_index": [
          "None is not of type 'integer'"
        ]
      },
      "message": "Request could not be processed.",
      "reason": "INVALID_REQUEST"
    }
  ],
  "state": "ERROR"
}
```

I would not expect this operation to work, but I think there might be a bug with the None here.

I deleted the VM, and tried again without disk size, created the VM as usual, this is second apply run:

```
htj@iridium:~/projects/ndn-iaas/tfntnx$ terraform apply
nutanix_subnet.vlan66: Refreshing state... (ID: 409dfe87-8c94-469b-ae6a-23f457ae586f)
nutanix_subnet.vlan67: Refreshing state... (ID: 5a3253fc-dec0-4fdd-b9a4-b532358ac2e6)
nutanix_virtual_machine.terraform-test-se-tug-ntp01_nordu_net: Refreshing state... (ID: b80c0f1a-40ca-4630-932f-38ab16baf2c3)

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

Success!

**Comment by JonKohler** [comment]
WRT Cloning and changing the disk size
This is an API bug (or lack of functionality, however you look at it), but I've previously opened a GH Issue (#160) to let people know about it.

We've already committed the fix for it internally, its just waiting for a release vehicle to go out the door

**Comment by htj** [comment]
Great. Our use case is the exact same as the guy in #160.

**Comment by JonKohler** [comment]
hey @marinsalinas - did we fix this naturally as part of the current sprint we're on? My memory says maybe, but I figure you might know

**Comment by JonKohler** [comment]
Need to validate resizing under https://github.com/terraform-providers/terraform-provider-nutanix/issues/23

And cloud_init related functionality needs a bit smoking out here: https://github.com/terraform-providers/terraform-provider-nutanix/issues/21

Moving this repo and issues to the upstream repo, so there is ONE single view of code and issues
