### ISSUE TITLE
client/v3/v3_service.go - clean up bunch of TODO's

### ISSUE THREAD

**Issue by JonKohler** [nutanix/terraform-provider-nutanix#127]
There are a ton of "ctx := context.TODO()" in the v3_service.go

Are these actually real TODO's? or are these dead code snippets?

**Comment by marinsalinas** [comment]
We need to add a context to make new http request and in golang we can use `context.TODO()` as a default context! 

You can see more details on : https://golang.org/pkg/context/#TODO
