### ISSUE TITLE
Missing user role association with nutanix_project ressource

### ISSUE THREAD

**Issue by acosteseque** [nutanix/terraform-provider-nutanix#141]
### Nutanix Cluster Information
Please provide the version of:
 - Nutanix Cluster (Prism Element / AOS): 5.17
 - Nutanix Prism Central: 5.17

### Terraform Version
Terraform v0.12.25
+ provider.nutanix last build from master

### Affected Resource(s)

* nutanix_project

### Terraform Configuration Files

```hcl
resource "nutanix_project" "project_test" {
  name        = "test-tf"
  description = "TEST TF"

  # categories {
  #   name  = "Environment"
  #   value = "Staging"
  # }

  default_subnet_reference {
    uuid = data.nutanix_subnet.prod.id
  }

  subnet_reference_list {
    uuid = data.nutanix_subnet.prod.id
  }

  user_reference_list {
    name = "anthony.costeseque@nxlab.fr"
    uuid = "279a7b1f-1d7a-5a81-8578-978938fe030d"
  }

  user_reference_list {
    name = "user1@nxlab.fr"
    uuid = "038c6af5-848a-54da-97e8-a62d5c588cd3"
  }

  user_reference_list {
    name = "user2@nxlab.fr"
    uuid = "0f5b3a7f-2c70-51a3-85c4-60c2d9afc36c"
  }

  # 20 vCPU / 40 GB RAM / 1 TB Storage
  resource_domain {
    resources {
      limit         = 20
      resource_type = "VCPUS"
    }
    resources {
      limit         = 42949672960
      resource_type = "MEMORY"
    }
    resources {
      limit         = 1099511627776
      resource_type = "STORAGE"
    }
  }
}
}
```
### Debug Output
Missing RBAC association to defined users in user_reference_list
Using API endpoint https://www.nutanix.dev/reference/prism_central/v3/api/access-control-policies/postaccesscontrolpolicies/

### Expected Behavior
Role definition to declared user in the project created using API endpoint https://www.nutanix.dev/reference/prism_central/v3/api/access-control-policies/postaccesscontrolpolicies/

### Actual Behavior
Users declared in the project but no role so it is not working

### Steps to Reproduce
create a project using nutanix_project ressource

**Comment by marinsalinas** [comment]
@yannickstruyf3  can you confirm that this is now working in our current implementation?

**Comment by yannickstruyf3** [comment]
> @yannickstruyf3 can you confirm that this is now working in our current implementation?

Yes this should be ok

**Comment by jantari** [comment]
This issue is talking about the master branch as of 16 Jun 2020, but I am using the release version 1.1.1 from 24 Nov 2020 and it doesn't have a `nutanix_project` resource type - is there any ETA on when that's coming out? I'd really want to use it.
