### ISSUE TITLE
Createing a VM with storage_config fails with "Additional properties are not allowed (u'storage_config' was unexpected)"

### ISSUE THREAD

**Issue by maxaudron** [nutanix/terraform-provider-nutanix#158]
### Nutanix Cluster Information
- Nutanix Element  5.10.9 LTS
- AHV Version Nutanix 20170830.270
- Nutanix Prism Central 5.16.1.1

### Terraform Version
```
Terraform v0.12.28
+ provider.nutanix v1.1.0
```

### Affected Resource(s)
* nutanix_virtual_machine

### Terraform Configuration Files
```hcl
variable "username" {
  type = string
}

variable "password" {
  type = string
}

provider "nutanix" {
  version      = "~> 1.1.0"
  username     = var.username
  password     = var.password
  endpoint     = "[redacted]"
  insecure     = true
  session_auth = true
  port         = 9440
}

data "nutanix_image" "ahv_base_image" {
  image_name = "ubuntu-18.04.3"
}

data "nutanix_cluster" "cluster" {
  name = "cf21-fujintx"
}

resource "nutanix_virtual_machine" "vm" {
  name         = "test_vm_disk_type"
  description  = "test"
  cluster_uuid = data.nutanix_cluster.cluster.metadata.uuid

  num_vcpus_per_socket = 4
  num_sockets          = 1
  memory_size_mib      = 4096

  disk_list {
    # disk_size_mib = var.root_disk_size_mib
    data_source_reference = {
      kind = "image"
      uuid = data.nutanix_image.ahv_base_image.id
    }

    device_properties {
      device_type = "DISK"
      disk_address = {
        device_index = 0
        adapter_type = "SCSI"
      }
    }

    storage_config {
      storage_container_reference {
        uuid = "481604c0-c4e5-4fbe-89e1-1250d8a80751"
      }
    }
  }
}
```

### Debug Output
https://gist.github.com/maxaudron/780941aba25e42250eab7002ff78941d

### Expected Behavior
The VM is created with a `storage_config` object under `spec.resources.storage_config`

### Actual Behavior
The VM is created with a `storage_config` object under `spec.resources.disk_list.0.storage_config`

### Steps to Reproduce
1. `terraform apply`

### Important Factors
The requests are made against a prismcentral.
​

**Comment by mathurin186** [comment]
I am curious about the outcome of this. I am experiencing the same problem.

**Comment by yannickstruyf3** [comment]
Hi @mathurin186 and @maxaudron ,

If I recall correctly, in order to use the `storage_container_reference` functionality the Prism Central and Prism Element version must be 5.17 or above.

Kind regards

**Comment by yannickstruyf3** [comment]
We will close this issue since the required information was provided. Please reach out to us in case there are additional questions.
