### ISSUE TITLE
Unit test for NewUploadRequest

### ISSUE THREAD

**Issue by JonKohler** [nutanix/terraform-provider-nutanix#161]
on https://github.com/nutanix/terraform-provider-nutanix/commit/c1a18361230badd10d2cd655e829c8c5d69db20f ... we added functions for uploading a local disk image

this commit did not come with an associated unit test, and has no coverage as a result.

There is a stub for NewUploadRequest test, but it does not have a test case associated with it.

**Comment by JonKohler** [comment]
Also applies to func (op Operations) UploadImage within v3 service

**Comment by htj** [comment]
I cannot get local upload to work. Have updated #48 with log from latest attempt.

**Comment by JonKohler** [comment]
@thetonymaster @marinsalinas @Crizstian - Can one of you guys loop back in and fix this? This was outstanding from the previous work

**Comment by thetonymaster** [comment]
@JonKohler will check this later. Since this is related to #48, did the call changed? I think I commented this on slack, but the function broke after the update to the test environment, did the request body changed?

**Comment by JonKohler** [comment]
hey @thetonymaster and @marinsalinas - can we circle back on this?
