### ISSUE TITLE
sysprep file in vm resource

### ISSUE THREAD

**Issue by cooperose** [nutanix/terraform-provider-nutanix#162]
### Nutanix Cluster Information
Please provide the version of:
 - Nutanix Cluster (Prism Element / AOS)
       5.15.1.1 LTS
 - Nutanix Prism Central
      5.17.1.1

### Terraform Version
Terraform v0.13.0
+ provider registry.terraform.io/terraform-providers/nutanix v1.1.0

### Affected Resource(s)
* nutanix_virtual_machine

### Terraform Configuration Files
resource "nutanix_virtual_machine" "testwin" {
  name                 = "win Test"
  description          = "Test win machine "
  provider             = nutanix
  cluster_uuid         = data.nutanix_cluster.cluster.id
  num_vcpus_per_socket = 1
  num_sockets          = 1
  memory_size_mib      = 2048
  nic_list {
    subnet_uuid = data.nutanix_subnet.vlan.id
  }
  guest_customization_sysprep = {
    install_type = "FRESH"
  }
  disk_list {
    disk_size_mib = 10000
    device_properties {
      device_type = "DISK"
      disk_address = {
        "adapter_type" = "SCSI"
        "device_index" = "0"
      }
    }
  }
  disk_list {
    data_source_reference = {
      kind = "image"
      uuid = nutanix_image.winserver2019.metadata.uuid
    }
  }
  disk_list {
    data_source_reference = {
      kind = "image"
      uuid = nutanix_image.nutanixvirtio.metadata.uuid
    }
  }
  depends_on = [nutanix_image.winserver2019, nutanix_image.nutanixvirtio]
}

### Debug Output

https://gist.github.com/cooperose/9e62a701cf2c9007d2b2a98f69f403bf

### Expected Behavior
Deployed windows vm using autounattended.xml file 

### Actual Behavior
received error code 422  "{u'install_type': u'FRESH'} is not valid under any of the given schemas"

### Steps to Reproduce
1. `terraform apply`

### Important Factors
Using prism central. Terraform plan and validate all report correct config. Apply fails when trying to create the vm. If you remove the guest_customization_sysprep section then the vm will deploy as expected. 
​

**Comment by yannickstruyf3** [comment]
@cooperose Can you test with following config:
```
  guest_customization_sysprep = {
    install_type = "FRESH"
    unattend_xml = base64encode(file("sysprep_autoattend.xml"))
}
```
where `sysprep_autoattend.xml` is the path to your unattend xml file?

Thanks

**Comment by yannickstruyf3** [comment]
@cooperose was the issue fixed by adding the unattend_xml line?

**Comment by yannickstruyf3** [comment]
We will close this issue due to inactivity. Please reach out to us in case of any additional questions or if we need to re-open the issue.
