### ISSUE TITLE
Example main.tf - guest_customization_cloud_init does not work

### ISSUE THREAD

**Issue by Tfindelkind** [nutanix/terraform-provider-nutanix#165]
**Describe the bug**
terraform shows an error that guest_customization_cloud_init key is unknown:
"...: invalid or unknown key: guest_customization_cloud_init"

**To Reproduce**
Try the example main.tf with guest customization.

**Versions (please complete the following information):**
 - OS WIN64 / gitBASH
 - Terraform v0.11.7
 - Nutanix Cluster 5.8
 - Nutanix Prism Central 5.8 

**Additional context**
Changing the example to make use of for example: guest_customization_cloud_init_user_data = "${base64encode(file("cloud-init.conf"))}" can solve the issue.

**Comment by JonKohler** [comment]
As part of our scope to enhance the example, can you add this there? Let's just test it, then comment it out, as not all customers will want to do this.

**Comment by JonKohler** [comment]
This is another good one for Hacktoberfest ... just an example update, but of course we'd need to make sure it works.

**Comment by Priteshkal** [comment]
Is there any update on this? I am also running into this same problem when I am trying to use guest_customization_cloud_init to set the hostname for a clone vm.

Thanks

**Comment by JonKohler** [comment]
Moved to https://github.com/terraform-providers/terraform-provider-nutanix/issues/21
