### ISSUE TITLE
nutanix provider doesn't appear in terraform registry

### ISSUE THREAD

**Issue by jehutyy** [nutanix/terraform-provider-nutanix#166]
It seems that terraform providers have been migrated to terraform registry but nutanix seems to be missing.

Because of that `terraform init` needs to create a `versions.tf` which interfere with air gap installation in a way that I have to include such a file in every repository i'm creating.

**Comment by gabybeitler** [comment]
We will be listed again in the terraform registry shortly.

**Comment by MaxPeal** [comment]
Any news or a ETA?

**Comment by gabybeitler** [comment]
@MaxPeal It is placed in the terraform registry as of this week.

**Comment by scorillo** [comment]
does not appear on the site
https://registry.terraform.io/search/providers?q=nutanix

**Comment by MaxPeal** [comment]
@gabybeitler is this realistic to see it in the registry or should we buy VMware licenses?

**Comment by gabybeitler** [comment]
We are working on 1.1.1 release which fixes this issue. It should be released very soon.

**Comment by gabybeitler** [comment]
@MaxPeal No need for those VMware licenses. Version 1.1.1 of our provider was just released. https://registry.terraform.io/search/providers?q=nutanix
