### ISSUE TITLE
Create a way to set a host name during clone of a VM

### ISSUE THREAD

**Issue by mpschmitt** [nutanix/terraform-provider-nutanix#167]
The VSphere provider gives you the ability to set a host name as you clone a new VM from an image. As far as I can tell, the Nutanix provider does not yet provide this ability (but please feel free to school me if that's wrong). The closest I think we can currently get is to use get_customization_sysprep (on Windows) and set the hostname in the sysprep itself. 

**Describe the solution you'd like**
It would be nice to just have a custom configuration block or something where params like hostname could be set. 

**Describe alternatives you've considered**
If there are any other ways to do it, please do just let me know.

**Comment by yannickstruyf3** [comment]
@mpschmitt 
Sysprep or cloud-init is currently the way to go to set a hostname in a virtual machine. 
Does sysprep/cloud-init in combination with Terraform templates (https://registry.terraform.io/providers/hashicorp/template/latest/docs/data-sources/file) fit your requirements? The templating mechanism will help in dynamically setting the hostname values.

**Comment by yannickstruyf3** [comment]
Did the provided information fix the issue? We will close the issue. Please reach out to us in case of additional questions or if we need to re-open.
