### ISSUE TITLE
'invalid memory address or nil pointer dereference' while getting a VM.

### ISSUE THREAD

**Issue by BiGOUDx** [nutanix/terraform-provider-nutanix#168]
### Nutanix Cluster Information
 - Nutanix Cluster Prism Element : 5.15 LTS
 - Nutanix Prism Central : pc.2020.8.0.1
### Terraform Version
Terraform v0.13.3
provider registry.terraform.io/terraform-providers/nutanix v1.1.0
### Affected Resource(s)
* data "nutanix_virtual_machine" "template_win2019"
### Terraform Configuration Files
```hcl
provider "nutanix" {
 username = "admin"
 password = "xxxxxxxxx"
 endpoint = "fqdn prism central"
 insecure = true
}

data "nutanix_virtual_machine" "template_win2019" {
  vm_id = "id of the vm"
}
```
### Panic Output
https://gist.github.com/BiGOUDx/1a5b502c26bfeb6cd04bc31948b6a2b3
### Expected Behavior
Get information from my template VM.
### Actual Behavior
Terraform crashes. A lot of errors appear.
### Steps to Reproduce
1. `terraform plan`
### Important Factors
I tried:
* with Prism Element 
* with Prism Central
* with Terraform 0.12.29

It's working with some VM (other ID). Some don't work. 
I cannot understand the common factor.

**Comment by yannickstruyf3** [comment]
Hi,

Would it be possible to execute the plan with following command and share the tf.log file?
`TF_LOG=trace TF_LOG_PATH=tf.log terraform plan`

Please make sure the logs do not contain sensitive information.

**Comment by BiGOUDx** [comment]
Sure. 
Here is the file: https://gist.github.com/BiGOUDx/e70b4fd459e545824041e114c95d90e0

**Comment by yannickstruyf3** [comment]
Thanks @BiGOUDx for sharing the log. 
This seems to be a bug in the provider when a data source is used on a VM that has following boot config:
```
"boot_config": {
    "boot_device_order_list": [
        "CDROM",
        "DISK",
        "NETWORK"
    ],
    "boot_type": "LEGACY"
},
```
I created a PR #169  that fixes this issue. Was able to reproduce and fix in my lab environment.

Kind regards

**Comment by BiGOUDx** [comment]
Correct. I changed the boot order and everything is fine now. Thanks for your help and the future fix.
