### ISSUE TITLE
Allow usage of service and address groups in network_security_rules

### ISSUE THREAD

**Issue by yannickstruyf3** [nutanix/terraform-provider-nutanix#170]
Since 5.18, two new object types can be used for network security rules:
- service_groups (https://www.nutanix.dev/reference/prism_central/v3/api/service-groups/postservicegroups/)
- address_groups (https://www.nutanix.dev/reference/prism_central/v3/api/address-groups/postaddressgroups)
for creating network_security rules.

The provider should be updated in order to offer this new functionality.

**Comment by Chup4Chups** [comment]
Hi @yannickstruyf3 , 

We are using terraform to create network security rules as we recently started to use Flow and I confirm it's very painful to not being able to use address_group and service_group.

do you have any update on this ?

**Comment by yannickstruyf3** [comment]
Hi,

Thank you for your message.
As far as I know this is still a roadmap item. No ETA yet.

**Comment by ebartz** [comment]
Is there any news on this issue?

**Comment by Chup4Chups** [comment]
Hi @siddharth-nutanix , @abhimutant, @yannickstruyf3 

Any ETA about the possibility to use address groups and service groups in network security rule ?
I am looking to do something like this:
```
app_rule_outbound_allow_list {
  address_group_inclusion_list = []
  service_group_list = []
}
```

**Comment by siddharth-nutanix** [comment]
Hi @Chup4Chups

[This PR](https://github.com/nutanix/terraform-provider-nutanix/pull/345) targets the functionality that you have mentioned. We will include it in the next release which is expected around 2nd week of March, 2022.

**Comment by abhimutant** [comment]
Closing this issue as PR is already merged.
