### ISSUE TITLE
breaking: ensure dhcp_options schema is accurate

### ISSUE THREAD

**Issue by JonKohler** [nutanix/terraform-provider-nutanix#170]
In short, dhcp_options schema for layer 3 managed networks isn't correct in 1.0 RC1.

This will be a breaking change for anyone using this in the existing alpha/beta/RC code.

Needs to be refactored across the board (RS, DS, documentation, and examples)

**Comment by JonKohler** [comment]
@marinsalinas it looks like you reverted my partial fixes for this, is that right? The challenge with this is that the DHCP Options section in the API has a bunch of stuff nested in it. 

I wanted to match them up so it made is straight forward on how terraform HCL would translate to to the API and vice versa.

lemme know

**Comment by marinsalinas** [comment]
Yes,  I reverted because it was causing problems, I think it's better to keep like I propose because terraform only allows maps with strings inside.

```hcl
	"dhcp_options": {
			Type:     schema.TypeMap,
			Optional: true,
			Computed: true,
			Elem: &schema.Resource{
				Schema: map[string]*schema.Schema{
					"boot_file_name": {
						Type:     schema.TypeString,
						Optional: true,
						Computed: true,
					},
					"domain_name": {
						Type:     schema.TypeString,
						Optional: true,
						Computed: true,
					},
					"tftp_server_name": {
						Type:     schema.TypeString,
						Optional: true,
						Computed: true,
					},
				},
			},
		},
		"dhcp_domain_name_server_list": {
			Type:     schema.TypeList,
			Optional: true,
			Computed: true,
			Elem:     &schema.Schema{Type: schema.TypeString},
		},
		"dhcp_domain_search_list": {
			Type:     schema.TypeList,
			Optional: true,
			Computed: true,
			Elem:     &schema.Schema{Type: schema.TypeString},
		},
```

I  moved `name_server_list` and `domain_search_list` to the schema's root.
It is OK for you?

**Comment by marinsalinas** [comment]
@JonKohler it is OK on the develop branch?

**Comment by JonKohler** [comment]
@marinsalinas Well, it would be nice if the schema in terraform matched the schema in the API. I have a feeling that a ton of early access folks on here do NOT use this feature, so now would be the time to make this change, such that the two areas match

**Comment by marinsalinas** [comment]
@JonKohler the thing here is if you want to match with the API putting  `domain_server_list` and `domain_search_list` inside `dhcp_options`  will not work because terraform only allows using strings inside a `TypeMap`.

The alternative is to make `dhcp_options` TypeSet or TypeList with one element on this types we are able to put whichever data type inside.

let me know if you want to keep all like this or make the change to TypeSet or TypeList.

**Comment by JonKohler** [comment]
@marinsalinas  remind me, where are we at with this? did we say just leave it as is? or are you doing a commit for this?

**Comment by JonKohler** [comment]
i believe we decided to leave this as-is
