### ISSUE TITLE
VM cloning

### ISSUE THREAD

**Issue by ranman166** [nutanix/terraform-provider-nutanix#177]
I'm trying to create a vm from either from cloning a snapshot or from a vm. I'm looking to do something comparable to a vcenter template. 

Looking at the docs it seems there is cloud-id, but I would rather just clone off of some golden image style template than install and customize. Then I see there is a parent-reference variable, but I'm not sure of the syntax of what a kind is reference.

Basically, I'm looking to skip the installation steps for a vm when it's booting up and just customize the memory, network, and storage as I need. 

Thanks!

**Comment by ranman166** [comment]
Oh, I think i might have found it with the data "nutanix_image". I'll close this once i test it.

**Comment by ranman166** [comment]
Yup seems good. Thanks!

**Comment by JonKohler** [comment]
Glad you got this sorted. For posterity, can you post your .tf code, so that others who may stumble upon this could get the same hints you got?

Thanks,
Jon

**Comment by ranman166** [comment]
Sure thing. Actually I didn't get it working quiet yet, but I found what I thought would be correct. I'm still having issues identifying if my "kind" and "uuid" are correct for cloning a vm.


```
  # What disk/cdrom configuration will this have?
  disk_list = [{
    # data_source_reference in the Nutanix API refers to where the source for
    # the disk device will come from. Could be a clone of a different VM or a
    # image like we're doing here
    data_source_reference = [{
      kind = "image"
      uuid = "f01e13b4-5d9e-4546-837d-08af3f555beb"
    }]

    # defining an additional entry in the disk_list array will create another
    # disk in addition to the image we're showing off above.
    device_properties = [{
      device_type = "DISK"
    }]
    disk_size_mib = 5000
  }]
}
```
My vm has a listed ID but not UUID does this matter or are they equivalent? Also the [references](http://developer.nutanix.com/reference/prism_central/v3/#Definitions-disk_reference) of "kind" that I am finding do not specify the available mappings.

Is there another reference available? The [git pages](https://nutanix.github.io/terraform-provider-nutanix/) seem down as well.

**Comment by JonKohler** [comment]
We're doing some heavy work on the project over the next week, so this may be a moot point here shortly. Let's keep it open to track, but would be good to re-test on rc2 when its available.

**Comment by JonKohler** [comment]
ok, reading through this again @ranman166 - I see what you're running into. The whole ID vs UUID thing is going to be fixed in the current development sprint, thats already being hacked away at. 

Nutanix calls everything internally UUID's within this API, so we're going to try to be consistent.

WRT Git pages - That shouldn't have been there in the first place, my mistake. #174 called this out just recently, so I've fixed that just now this evening.

Anyhow, boiling this back, there are a few ways to do what you're trying to do: 
1) Creating your "gold image" as a disk within the image service in AHV, which is exposed in terraform as an nutanix_image, and clone it as the data_source_reference. I think this is a bit clunky in terraforms use case.

2) use the nutanix_image data source to declare that the image itself is an object that could be highly reusable in our terraform spec, and then call the UUID from THAT within the resource definition (which is the code snippet you posted), instead of calling a native UUID.

This is more terraform-esque IMHO.


Either way, give us a bit of time to cut another RC so we can do this nice and cleanly

**Comment by ranman166** [comment]
Ok that's the direction I was going initially. The "nutanix image" default metadata entry was giving me errors, so I pulled it out to see what the issue was. 

From some different sources I've found out that the "ID" listed in prism is the same as the UUID returned from the ncli api calls (ncli vm ls name=****), so I believe the id I have above should work. I was also informed that for the disk reference the kind only has "disk" as a attribute so that answers that. 

I think I have enough to work with.  Below is the original error I had that me either think that A) the id is wrong or B) the kind is incorrect. 


```
Error: Error refreshing state: 1 error(s) occurred:

* data.nutanix_image.test: 1 error(s) occurred:

2018-09-07T08:31:40.053-0500 [DEBUG] plugin.terraform-provider-nutanix: 2018/09/07 08:31:40 [ERR] plugin: stream copy 'stderr' error: stream closed
* data.nutanix_image.test: data.nutanix_image.test: error: {
  "api_version": "3.1",
2018-09-07T08:31:40.053-0500 [DEBUG] plugin.terraform-provider-nutanix: 2018/09/07 08:31:40 [ERR] plugin: plugin server: accept unix /var/folders/f5/j2n9w25x6ljfmh1mz4dg7z95rp4_n7/T/plugin842253168: use of closed network connection
  "code": 404,
  "kind": "image",
  "message_list": [
    {
      "message": "image : bb13db2c-9cbc-449d-baf3-553bc3a8b2c6 does not exist.",
      "reason": "ENTITY_NOT_FOUND"
    }
  ],
  "state": "ERROR"
}
```

It may still be the incorrect id. Maybe it should be some component of the vm rather than the vm's specific id. I'll play around. Thanks for all of your hard work!

**Comment by ranman166** [comment]
Ohhh, I just read some of the docs. My endpoint is going towards prism and not prism central. I'm assuming that is the issue then. Otherwise I'm at a loss.

**Comment by ranman166** [comment]
Ok, I have access to prism central now; however, I am still have issues.  All of the examples you have are using images. Do you have an example of cloning from a vm? 

I'm having issues with defining a vm as an image. 
```
 data "nutanix_virtual_machine" "nutanix_virtual_machine" {
   vm_id = "f01e13b4-5d9e-4546-837d-08af3f555beb"
 }
data "nutanix_image" "test" {

    #kind = "VM"
    #UUID = "nutanix_virtual_machine.nutanix_virtual_machine.uuid"
    image_id = "${data.nutanix_virtual_machine.nutanix_virtual_machine.id}"
    
}

Even trying to bypass the nutanix image, it doesn't like any "kind" i put into the disk reference, although I believe it should be "DISK".
```

**Comment by JonKohler** [comment]
We can mock up an example. Give us a bit of time to re-stablized the develop branch, as that is what we're solely focused on right now. Not that we dont want to help, just that we've got a big ole chunk of work to do, and there may be changes.

**Comment by ranman166** [comment]
Bump, just wondering if there is any progress with this. Thanks!

**Comment by JonKohler** [comment]
@marinsalinas can you look at this?

**Comment by marinsalinas** [comment]
Hello @ranman166 

The following configuration shows how to copy the image_id from VM datas_source to new VM, let me know if it works for you:

```hcl
data "nutanix_clusters" "clusters" {}

#Prework - you have already the image and vm created
resource "nutanix_image" "cirros-034-disk" {
  name        = "test-image-dou"
  source_uri  = "http://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-disk.img"
  description = "heres a tiny linux image, not an iso, but a real disk!"
}

resource "nutanix_virtual_machine" "vm1" {
  name = "test-nutanix-vm"

  cluster_reference = {
    kind = "cluster"
    uuid = "${data.nutanix_clusters.clusters.entities.0.metadata.uuid}"
  }

  num_vcpus_per_socket = 1
  num_sockets          = 1
  memory_size_mib      = 186

  disk_list = [{
    data_source_reference = [{
      kind = "image"
      uuid = "${nutanix_image.cirros-034-disk.id}"
    }]
  },
    {
      disk_size_mib = 100 #extra disk
    },
  ]
}


#get the VM by id 
data "nutanix_virtual_machine" "vmds" {
  vm_id = "${nutanix_virtual_machine.vm1.id}" #you should set your vmID here
}

#Create new vm here
resource "nutanix_virtual_machine" "vm2" {
  name = "test-nutanix-vm"

  cluster_reference = {
    kind = "cluster"
    uuid = "${data.nutanix_clusters.clusters.entities.0.metadata.uuid}"
  }

  num_vcpus_per_socket = 1
  num_sockets          = 1
  memory_size_mib      = 186

  disk_list = [{
    data_source_reference = [{
      kind = "image"
      uuid = "${data.nutanix_virtual_machine.vmds.disk_list.1.data_source_reference.uuid}" #set data_source(image) id from vm data source.
    }]
  }]
}
```

Let me know if is there any issue with the configuration.

P.S. This works on the develop branch.

Thanks!

**Comment by JonKohler** [comment]
@ranman166 can you retry this with the develop branch, with Marin's comments above? Please reopen the ticket if you've still seen an issue there

**Comment by ranman166** [comment]
Still having issues, but It might be because I'm am working on the release provisioned. I'll test it using the develop branch when I can get that chance. 

I also thought it might be because I am trying to use a vm not created by terraform to clone, but just testing this verbatim results in errors.

Thanks for all you help.

**Comment by JonKohler** [comment]
You need to use the develop branch

**Comment by Priteshkal** [comment]
Hi,

I am working with @ranman166 on this same issue and will be following up on this. 

I have been trying to test this with the solution provided by @marinsalinas but without provisioning 2 VM's but rather using a UUID of an already provisioned VM on AHV -- this is failing with the following error.
```
Error: Error applying plan:

1 error(s) occurred:

* nutanix_virtual_machine.vm2: Resource 'data.nutanix_virtual_machine.vmds' does not have attribute 'disk_list.1.data_source_reference.uuid' for variable 'data.nutanix_virtual_machine.vmds.disk_list.1.data_source_reference.uuid'
```

I think this is because in the example provided by @marinsalinas, when we give the uuid as:
```
disk_list = [{
    data_source_reference = [{
      kind = "image"
      uuid = "${data.nutanix_virtual_machine.vmds.disk_list.1.data_source_reference.uuid}" #set data_source(image) id from vm data source.
    }]
  }]
```
its referencing the resource which is referencing the ISO and not making a clone of the disk.

**My Requirement**
I am trying to clone a pre-existing VM with the ability to customize the hostname using this provider.

How do I go about this?

Thanks
