### ISSUE TITLE
Can't apply just a single resource "nutanix_image"

### ISSUE THREAD

**Issue by guglez** [nutanix/terraform-provider-nutanix#18]
Hi @JonKohler ,

I'm doing initial configuration of terraform with nutanix. I defined only one resource:

```
resource "nutanix_image" "cirros-034-disk" {
    name        = "cirros-034-disk"
    source_uri  = "http://download.cirros-cloud.net/0.3.4/cirros-0.3.4-x86_64-disk.img"
    description = "heres a tiny linux image, not an iso, but a real disk!"
}
```

I expect that terraform will create an image on my cluster.
However I have this error:

```
Error: Error applying plan:

1 error(s) occurred:

* module.nutanix.nutanix_image.cirros-034-disk: 1 error(s) occurred:

* nutanix_image.cirros-034-disk: failed to read image with name(cirros-034-disk): json: cannot unmarshal string into Go struct field MessageResource.details of type map[string]interface {}

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

```

I also can't create a vm from example config. Could you please take a look here?

**Comment by olljanat** [comment]
@guglez which Prism Central version you are using?

It looks to be that CE version 2018.05.17 does not have this issue but paid version 5.10.0.1 have.

**Comment by marinsalinas** [comment]
> @guglez which Prism Central version you are using?
> 
> It looks to be that CE version 2018.05.17 does not have this issue but paid version 5.10.0.1 have.

@guglez Can you share the prism central version that you are using?

Thanks

**Comment by guglez** [comment]
Hi @marinsalinas 

Right now I do not have PC at all. It died because of the time/ntp issue and I need to recreate it. I'm working on this with Nutanix support.

**Comment by marinsalinas** [comment]
Well, closed due is not in the scope.
