### ISSUE TITLE
local resource nutanix_image

### ISSUE THREAD

**Issue by jehutyy** [nutanix/terraform-provider-nutanix#182]
I would like to use a local iso to create a resource nutanix_image. 

Is there a way to do so without using a http server ?

**Comment by yannickstruyf3** [comment]
Hi @jehutyy,

Can you test if this code works for you:

```
resource "nutanix_image" "local_image_upload" {
  name        = "local-image-cirros-030"
  source_path = "cirros-0.3.0-x86_64-disk.img" # <== path to local image
  description = "locally uploaded image"
}
```

**Comment by jehutyy** [comment]
thanks a lot, that works well ;)

**Comment by jehutyy** [comment]
Your solution is working fine except for a border effect. 
Using `source_path` my iso is not tagged as ISO and thus cannot be used as cdrom.

Have you heard of something like this ?

**Comment by gabybeitler** [comment]
This appears to be a bug in the implementation.

**Comment by jehutyy** [comment]
Thanks a lot for this PR, will this patch be included in next release ? 
Would it be a possibility to keep me updated on that matter ?
