### ISSUE TITLE
Disk not created with VM?

### ISSUE THREAD

**Issue by thetonymaster** [nutanix/terraform-provider-nutanix#183]
After creating a Virtual machine with an image and a disk this is the output of the plan.

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ nutanix_virtual_machine.demo-01-web
      disk_list.0.disk_size_mib: "44" => "5000"

Plan: 0 to add, 1 to change, 0 to destroy.

**Comment by JonKohler** [comment]
Tony and I figured this out. There was a syntax issue on the state file that caused this to blow up. We resolved this in slack without a code fix.
