### ISSUE TITLE
Unexpected behavior when refreshing VM state

### ISSUE THREAD

**Issue by benaka47** [nutanix/terraform-provider-nutanix#187]
Hi

I'm creating a VM like follows :
```

data "nutanix_image" "os_disk"{

  image_id = "7c357add-2217-4b65-9f46-8f4d22218311"
}

resource "nutanix_virtual_machine" "terraform-01-test" {

  name                 = "from_terraform"
  description          = "Provisioned by terrafrom"
  num_vcpus_per_socket = 2
  num_sockets          = 1
  memory_size_mib      = 4096
  power_state          = "ON"

  cluster_reference = {
    kind = "cluster"
   uuid = "00053fec-afbb-b877-70ea-7cd30ab93d00"

  }
  nic_list = [{
    subnet_reference = {
     kind = "subnet"
      uuid = "52180766-de94-4eec-9d03-85760d757570"
   }
  }]

  disk_list = [{
      data_source_reference = [{
        kind = "image"
        uuid = "7c357add-2217-4b65-9f46-8f4d22218311"
      }]

      device_properties = [{
        device_type = "DISK"
      }]
    },
    {
    device_properties = [{
      device_type = "DISK"
    }]
    disk_size_mib = 5000
  }]
}

output "id" {
  value = "${nutanix_virtual_machine.terraform-01-test.id}"
}


```
The virtual machine is successfuly created, but when rerunning 

> terraform apply
 
terraform is asking to create a new VM ressource 

`Plan: 1 to add, 0 to change, 0 to destroy.`

This led me te verify if the refresh is actually working so i ran

> terrafrom refresh 
> data.nutanix_image.os_disk: Refreshing state...
> nutanix_virtual_machine.terraform-01-test: Refreshing state... (ID: 9c451345-277e-42bd-9978-e3d5b98ff4f1)

when I checked the terraform.state file, the "nutanix_virtual_machine.terraform-01-test" block disappered 

Environnement: Win64 , terraform v 0.11.8
Tested with RC1 Binary and compiled Master branch (10/09/2018)

Attached the log from terraform refresh
[terraform.log](https://github.com/nutanix/terraform-provider-nutanix/files/2379211/terraform.log)

**Comment by JonKohler** [comment]
Hey @benaka47  - thanks for the report. Note, we've been doing a metric ton of work post-rc1 in to the develop branch, and have not yet forked rc2 or synced develop to master.

As such, you'd want to retry this by compile from develop HEAD instead of rc1 or master.

Note though - we've got a little bit to go before we cut rc2, but this is under active development right now

**Comment by benaka47** [comment]
Thank you @JonKohler ! 
 The VM ressource refresh is working fine with the develop branch

**Comment by JonKohler** [comment]
Thanks for reverting back, closing this out since you mentioned its working from develop
