### ISSUE TITLE
ip_address not available as nutanix_virtual_machine attribute.

### ISSUE THREAD

**Issue by rmatinata** [nutanix/terraform-provider-nutanix#19]
**Describe the bug**
ip_address not available as nutanix_virtual_machine attribute.

```
output "ips" {
 value = "${join(",",nutanix_virtual_machine.simple-vm.*.ip_address)}"
}

Error: Error running plan: 1 error(s) occurred:

* output.ips: Resource 'nutanix_virtual_machine.simple-vm' does not have attribute 'ip_address' for variable 'nutanix_virtual_machine.simple-vm.*.ip_address'
``` 

**Expected behavior**
ip_address available as an attribute.

**Versions (please complete the following information):**
 - CentOS 7.x
 - Terraform 0.11.11
 - Nutanix Cluster 5.10.07
 - Nutanix Prism Central 5.10.07
 - Terraform provider version - compiled from master

**Additional context**

It seems that this problem was originated by this commit: 5315889b9bd692eb1ca718301f28918938cb9273

This creates a very serious problem since due to Terraform interpolation limitations (can't deal with complex nested lists), we can't really access IP addresses (such as for filling up templates), when creating VMs in bulk. The following construct would simply not work:

```
output "simple-vm-ips" {
  value = "${join(",",nutanix_virtual_machine.simple-vm.*.nic_list.0.ip_endpoint_list.0.ip)}"
}
```

**Comment by marinsalinas** [comment]
Hello @rmatinata, 

We know about the Terraform's interpolation syntax has limitations, we are figuring out how to solve this. The previous code (5315889) is no longer available since you could have more than one NICs attached with multiple IP endpoints. The following output code might work for you if you are trying to get the VM.

```hcl
output "ip_address" {
  value = "${lookup(nutanix_virtual_machine.vm.nic_list.0.ip_endpoint_list[0], "ip")}"
}
```

For more information see: #17

**Comment by PacoDw** [comment]
To due to a inactivity of this issue we will close this ticket, if you still having similar issues like this, plz open a new one.
