### ISSUE TITLE
Add VM Power States constants on client

### ISSUE THREAD

**Issue by thetonymaster** [nutanix/terraform-provider-nutanix#194]
Create a `PowerState`type and a set of variables that describe each of the power states on the VM, such as `PowerState_ON`, PowerState_OFF, etc.

**Comment by JonKohler** [comment]
This would be another good one for Hacktoberfest, seems like it could be low hanging for an external contributor.

That said, if it doesn't get accomplished that way, we'll want to do it any way we can.

**Comment by JonKohler** [comment]
When @marinsalinas and I were discussing this previously, I believe we agreed that we're not going to expose powerstates, similar to other public cloud providers, where VM instances are either ON (from a desired state perspective), or non-existant
