### ISSUE TITLE
Bug | Resource subnet | not possible to set ip_config_pool_list_ranges

### ISSUE THREAD

**Issue by MuellerMH** [nutanix/terraform-provider-nutanix#196]
**Describe the bug**
If you want to configure a managed subnet with automatic IP address assignment with the resource subnet, you have to define an IP range so that VMs can be assigned later. If you set the parameter in the resource subnet, the RegEx validate will fail.

```
 nutanix_subnet.bastion-subnet: error: {
  "api_version": "3.1",
  "code": 422,
  "message_list": [
    {
      "details": {
        "spec.resources.ip_config.pool_list.0.range": [
          "u'10.21.52.100' does not match '^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)[ ](?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'"
        ],
        "spec.resources.ip_config.pool_list.1.range": [
          "u'10.21.52.109' does not match '^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)[ ](?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'"
        ]
      },
      "message": "Request could not be processed.",
      "reason": "INVALID_REQUEST"
    }
  ],
  "state": "ERROR"
}
```

**To Reproduce**
1. Create a subnet resource
```
variable "cluster_id" {}
// no data nutanix_clusters used because terraform will crash.
resource "nutanix_subnet" "kube-subnet" {   
    cluster_reference = {
        kind = "cluster"
        uuid = "${var.cluster_id}"
    }
    name="kube-subnet"
    vlan_id=2
    subnet_type="VLAN"  
    default_gateway_ip = "10.21.52.1"
    subnet_ip = "10.21.52.0"
    prefix_length= 24
    ip_config_pool_list_ranges= [
        "10.21.52.110",
        "10.21.52.250"
    ]
    dhcp_server_address={
        ip="10.21.52.254"
    }
    dhcp_options {
		boot_file_name   = "bootfile"
		domain_name      = "nutanix"
		tftp_server_name = "10.21.52.200"
  }
  dhcp_domain_name_server_list = ["8.8.8.8", "4.2.2.2"]
}
```
2. Add DHCP and Ip Config Pool
3. Apply with terraform

**Expected behavior**
I would expect the subnet to be configured accordingly after creation and to have an IP range poll. If you let the ip_config_pool_list_ranges out of the resource and set them manually via the GUI this works. This should also work with the resource itself.

**Screenshots**
![bildschirmfoto 2018-09-21 um 09 40 52](https://user-images.githubusercontent.com/3248340/45866947-8041e380-bd82-11e8-8c75-2a9420af9e08.png)

**Versions (please complete the following information):**
 - macOS HighSierra  V: 10.13.6 (17G2307)
 - Terraform Terraform v0.11.8
-  Version 5.6 - Starter License
-  NCC Version: 3.5.1
-  LCM Version: 1.4.f2bd889

**Comment by marinsalinas** [comment]
Hello @MuellerMH 

The issue here is you should set this field with the following regex `"^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)[ ](?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$"` that means you have to set all the range in one element in  `ip_config_pool_list_ranges` array.


The following configuration should work for you:
```hcl
variable "cluster_id" {}
// no data nutanix_clusters used because terraform will crash.
resource "nutanix_subnet" "kube-subnet" {   
    cluster_reference = {
        kind = "cluster"
        uuid = "${var.cluster_id}"
    }
    name="kube-subnet"
    vlan_id=2
    subnet_type="VLAN"  
    default_gateway_ip = "10.21.52.1"
    subnet_ip = "10.21.52.0"
    prefix_length= 24
    ip_config_pool_list_ranges= [
        "10.21.52.110 10.21.52.250" #set all two IPs together in one string element.
    ]
    dhcp_server_address={
        ip="10.21.52.254"
    }
    dhcp_options {
		boot_file_name   = "bootfile"
		domain_name      = "nutanix"
		tftp_server_name = "10.21.52.200"
  }
  dhcp_domain_name_server_list = ["8.8.8.8", "4.2.2.2"]
}
```


Thanks!
