### ISSUE TITLE
"No permission to access the resource. \u003cRequest 'http://xxxxx:9440/v3/vms' [POST]\u003e"

### ISSUE THREAD

**Issue by diegomezgarcia87** [nutanix/terraform-provider-nutanix#199]
Hi guys

i've been trying to use TF provider to create a VM, so when i apply the changes the response is 403 error code.

* nutanix_virtual_machine.manager: error: {
  "api_version": "3.1",
  "code": 403,
  "message_list": [
    {
      "message": "No permission to access the resource. \u003cRequest 'http://xxxxx:9440/v3/vms' [POST]\u003e",
      "reason": "ACCESS_DENIED"
    }
  ],
  "state": "ERROR"
}

Furthermore i'm able to create a VM using the API without any problems

This is my provider config block

provider "nutanix" {
  username = "${var.ntx_usr}"
  password = "${var.ntx_pwd}"
  endpoint = "xxxxx"
  insecure = true
  port     = 9440
}

Thanks guys, great work

**Comment by phantomis** [comment]
Same here, facing the same problem.

**Comment by JonKohler** [comment]
Hey folks - when you hit create issue > bug report here on GH, it had a bit of a template to help capture some info

Specifically - 
**Versions (please complete the following information):**
 - OS
 - Terraform
 - Nutanix Cluster
 - Nutanix Prism Central

Also 
1) Can you post the relevant snippets from your main.tf beside the provider configuration?
2) What version of the terraform provider? Are you using the posted rc1? Did you compile from develop? Did you compile from master? or what?

**Comment by phantomis** [comment]
Sorry, y just realized the template you said. 

From my side: 

OS: Fedora 28
Terraform: v0.11.8
Nutanix Cluster: ?
Nutanix Prism Central: 5.8
Terraform-provider-nutanix: rc1

main.tf file 
```
provider "nutanix" {
  username = "xxxx"
  password = "xxxx"
  endpoint = "xxxxx"
  insecure = true
  port     = 9440
}

resource "nutanix_virtual_machine" "vm1" {
  name = "test-dou-update-15"

  description = "test update 4"

  num_vcpus_per_socket = 1
  num_sockets          = 1
  memory_size_mib      = 1024
  power_state          = "ON"

  nic_list = [
    {
      subnet_reference = {
        kind = "subnet"
        uuid = "6e58a294-3bc1-4826-a173-72874464804a"
      }
    }
  ]

  disk_list = [{
    device_properties = [{
      device_type = "DISK"
    }]


    disk_size_mib = 10000
  }]
}
```

Error: 

Expected: create a VM
Actual: Error calling the API with the message; 
```

**Comment by JonKohler** [comment]
We're on the cusp of releasing RC2, which has a metric ton of improvements. RC1 has quite a few issues, especially with AOS 5.8

If you're comfortable building the provider (which the readme.md has instructions for), do that from the develop branch, and retry this. 

If it still doesn't work, please let us know. Otherwise, if you could wait for a few days for rc2, we'll get that posted.

**Comment by diegomezgarcia87** [comment]
Hi Jon

I builded the provider from develop branch updated to yesterday (09/27). Another antecedent is we are pivoting to another machine with ssh tunnel. For some reason the plugin change the API request path form /api/nutanix/v3/vms to /v3/vms when i use nutanix server IP.

**Comment by JonKohler** [comment]
ok, that doesn't make any sense. If this was the case, literally nothing would work, so something is wrong somewhere.

@marinsalinas @thetonymaster can you help debug here?

**Comment by diegomezgarcia87** [comment]
Hi guys i have more information regarding this issue, Prismcentral has been updated to 5.8.2 version and now has ssl certs enabled.

when i want to create an VM with TF provider i have the next error:

**No permission to access the resource. \u003cRequest 'http://ntxprismctral.server.cl:9440/v3/vms' [POST]\u003e"**

The weird is that the URL changed from **https** to **http** and the PATH from **/api/nutanix/v3/vms** to **/v3/vms**

Do you have some idea what could be happening.

Thanks

**Comment by diegomezgarcia87** [comment]
Hello again guys, the issue was i missed project_reference property, so i was using the default project and i cant create VMs on it.

**Comment by JonKohler** [comment]
closing this out, meant to close a while back with @diegomezgarcia87's comment above
