### ISSUE TITLE
Example main.tf - guest_customization_cloud_init does not work

### ISSUE THREAD

**Issue by JonKohler** [nutanix/terraform-provider-nutanix#21]
Moved from: https://github.com/nutanix/terraform-provider-nutanix/issues/165

**Describe the bug**
terraform shows an error that guest_customization_cloud_init key is unknown:
"...: invalid or unknown key: guest_customization_cloud_init"

**To Reproduce**
Try the example main.tf with guest customization.

**Versions (please complete the following information):**
 - OS WIN64 / gitBASH
 - Terraform v0.11.7
 - Nutanix Cluster 5.8
 - Nutanix Prism Central 5.8 

**Additional context**
Changing the example to make use of for example: guest_customization_cloud_init_user_data = "${base64encode(file("cloud-init.conf"))}" can solve the issue.

**Comment by marinsalinas** [comment]
Hello @JonKohler, regarding with this issue, I didn't see any guest_customization_cloud_init field in the configuration of main.tf.

Could you provide the actual main.tf file for this issue?
