### ISSUE TITLE
Datasources for categories

### ISSUE THREAD

**Issue by ranman166** [nutanix/terraform-provider-nutanix#217]
We are looking to be able to reference categories without having them managed as resources.

For instance, we want to be able to create a bunch of category keys and later have users add values if needed and reference them within their vm creation without having users create or destroy the keys.

A win would be referencing them without having to deal with the "id" within the vm resource. We could do this through local variables in a module, but managing their "values" will get out of hand.

**Comment by JonKohler** [comment]
Hey @ranman166, my apologies on the slow responses to everything over the past several weeks. Dealing with a death in the family that hit me harder than expected, and other work deliverables led to terraform slipping through the cracks big time. 

I'm going to move this over to https://github.com/terraform-providers/terraform-provider-nutanix, and archive this repo, as the terraform-providers is the "upstream" go-forward version

**Comment by ranman166** [comment]
I totally understand. Sorry for your loss.
