### ISSUE TITLE
DR Runbook support

### ISSUE THREAD

**Issue by JonKohler** [nutanix/terraform-provider-nutanix#22]
from @marcelkleine on https://github.com/nutanix/terraform-provider-nutanix/issues/219

> Can the new DR functionality (Runbooks etc) be added to the TerraForm provider as resources?
> How do we make sure new features in PC are added as resources in Nutanix TF provider?

This functionality is exposed from Prism Central, so this would need to become a new resource/datasource/etc within the current codebase framework.

**Comment by coderGo93** [comment]
The [PR](https://github.com/terraform-providers/terraform-provider-nutanix/pull/125) for this issue has been made
