### ISSUE TITLE
Specifying container uuid

### ISSUE THREAD

**Issue by skippy39us** [nutanix/terraform-provider-nutanix#222]
One of the things I'm attempting to do is specify a container uuid on which to build a VM in nutanix.  Currently, I can't seem to do that.  The ramifications of this are that all VMs built are placed on the default container, no matter what.  And currently, moving VMs off of this container onto another is a non-trivial matter. 

It'd be nice if I could just specify the right container uuid as part of the disk_list stanza. 

I've tried specifying a volume_group that has a container that would be acceptable given our storage requirements, this only results in a VM without _any_ disk. 

Is it possible to achieve this?

**Comment by JonKohler** [comment]
In short, no. What is the use case you're trying to achieve, besides just getting it out of the default container?

I'm not hating at all, I've had this conversation before, I'm just curious what your take/approach is on it and make sure we understand the use case.

WRT "container targeting"
Long story short, but we're working on it at an API level as part of another project. Once that is available in API, we could plumb it into terraform

**Comment by JonKohler** [comment]
Hey, circling back as we should move this conversion to the upstream repo, here: https://github.com/terraform-providers/terraform-provider-nutanix

Please do carry this forward there, as this repository will now defer to that one as the single source of truth.
