### ISSUE TITLE
Ability to resize a vdisk when deploying from image resource

### ISSUE THREAD

**Issue by JonKohler** [nutanix/terraform-provider-nutanix#23]
from https://github.com/nutanix/terraform-provider-nutanix/issues/160

The situation as reported by leonteq:
> The resizing of the disk; the Ubuntu cloud image is relatively small, if we ask for the disk to be resized, it fails to resize – would be good if that could happen

Answer from Jon
> We’ve fixed this in AOS 5.8.1, which should be out in 4-5 weeks. This fix missed the 5.8 shipping gate, so it will come on the next round.
> When that release comes out, all you need to do is specify the disk size when you specify datasource_reference, and the API will do what you’d think it SHOULD do ☺

Scope of work here is to validate that the resizing API works as expected. Given 5.6 thru 5.9 releases are short term support, I dont suspect we need to add version-specific checking logic for this, but rather say that the provider is supported on 5.10.x++ releases, which is the next long term train now GA as of December

**Comment by marinsalinas** [comment]
I've asked to the Team if I can get a JSON example for this feature, then, I can change it using terraform configuration and test it.

**Comment by marinsalinas** [comment]
Fixed on https://github.com/terraform-providers/terraform-provider-nutanix/tree/vdisk-update-%2323
