### ISSUE TITLE
Add additional acceptance test configurations for nutanix resources and data sources

### ISSUE THREAD

**Issue by JonKohler** [nutanix/terraform-provider-nutanix#24]
Moved from https://github.com/nutanix/terraform-provider-nutanix/issues/150

**Is your feature request related to a problem? Please describe.**
We need to get at least 50% of code coverage to get the Hashicorp validation.

**Describe the solution you'd like**
We need to add more configurations in acceptance tests using more arguments than we have.

For example: 
In `network_security_rules` resource and data source we need configuration using related arguments/attributes of:
* `quarantine_rule` argument.
* `isolation_rule` argument.

In `virtual_machine` resource and data source we need configuration using related arguments/attributes of:
* `guest_customization` argument.   
* `boot_config` argument.
* `categories` argument.
* `nic_list` argument.
* `guest_toolds` argument
* `gpu_list` argument
* `disk_list` argument

Other resources and data sources is not covered the parts of code related to `availability_zone_reference`, `categories`, `project_reference` argurments/attributes.

We need a real example of `volume_group` resource currently we don't have it.

**Describe alternatives you've considered**
None for now.

**Additional context**
Here is the `coverage.html` where you can see with the current test in which parts of the code are not being covered.

https://gist.github.com/marinsalinas/a7b0665444a15ecc4061518b0c9703f9

**Comment by marinsalinas** [comment]
We added many test cases in the latest PR we made.

See master branch.
