### ISSUE TITLE
Set storage_container for image

### ISSUE THREAD

**Issue by marcelvenema** [nutanix/terraform-provider-nutanix#249]
To create an image, i can do : 
resource "nutanix_image" "W2K19" {
  name        = "W2K16"
  description = "Windows Server 2019"
  source_uri  = "https://<URL>/W2K19.iso"
  checksum    = { checksum_algorithm = "SHA_256", checksum_value ="9976b3e125050542ca50de3c7347d132113834edc151c64c55f9e30bc4d2160f" }
}
This results in creating the image in the SelfServiceContainer. I want to create an image in another storage container. How can I do this?

**Comment by zisuu** [comment]
@marcelvenema check out this issue and I guess it answers your question?  https://github.com/nutanix/terraform-provider-nutanix/issues/223

**Comment by nnorakk** [comment]
@zisuu @marcelvenema  I have the same error here. There is no option to choose to what storage container the image will go and when define in vm another storage_container_reference like #223  the resulted vm ignores and keep in SelfServiceContainer , the same container where the image was. 

Any thoughts?

**Comment by zisuu** [comment]
@nnorakk I did not find a way to create a vm or disk and specify the storagecontainer. Maybe this "limitation" is also what some people wrote on here: https://next.nutanix.com/how-it-works-22/prism-api-v3-image-upload-define-storage-container-37329 ?

**Comment by premkarat** [comment]
Not possible using v3 API, if this supported in v4 then we can relook at it.
