### ISSUE TITLE
data "nutanix_subnets" "main" {} output limited to 20 subnets

### ISSUE THREAD

**Issue by bavivek2003** [nutanix/terraform-provider-nutanix#256]
### Nutanix Cluster Information
 - Nutanix Prism Central : pc.2020.11
### Terraform Version
tried terraform version 12.x and 13.x
### Affected Resource(s)
nutanix_subnets
### Terraform Configuration Files
```
data "nutanix_subnets" "main" {}
```
### Expected Behavior
the output should list all the subnets.(i have around 200+ subnets)
### Actual Behavior
the output is limited to 20 subnets.
### Steps to Reproduce
1. `terraform apply`
#### Important Factors
i was trying to use length like API form but im getting error as mentioned below.
```
data "nutanix_subnets" "main" {
      metadata = {
    length = 30
  }
}
```
###output when i use length
```
 on main.tf line 6, in data "nutanix_subnets" "main":
   6:       metadata = {
```

**Comment by yannickstruyf3** [comment]
Hi,

This should be fixed in provider version 1.2.1. Issue will be closed. Please reach out to us in case of additional questions.
