### ISSUE TITLE
[nutanix_karbon_cluster] kube-apiserverauth credentials (v1.2.0)

### ISSUE THREAD

**Issue by kruftik** [nutanix/terraform-provider-nutanix#258]
**Is your feature request related to a problem? Please describe.**
Since the nutanix_karbon_cluster resource output does not contain any JWT tokens or so,  it's not possible to call kubernetes APIs to deploy apps or somehow else use the provisioned cluster without calling a Nutanix raw API to retrieve the token

**Describe the solution you'd like**
it'd be useful to enrich the resource output with auth credentials of default user, either by a separate Nutanix API call or by extending the API method itself

**Describe alternatives you've considered**
local-exec terraform provisioner, external data source, uri ansible module or bare curl invocation

**Comment by yannickstruyf3** [comment]
@kruftik Does this data source meet your requirements:
https://registry.terraform.io/providers/nutanix/nutanix/latest/docs/data-sources/karbon_cluster_kubeconfig

This will allow you to fetch the kubeconfig data from the karbon cluster via Prism Central APIs

**Comment by premkarat** [comment]
Its already implemented
