### ISSUE TITLE
Add ability to specify cluster in network and subnet data blocks

### ISSUE THREAD

**Issue by gfenn-newbury** [nutanix/terraform-provider-nutanix#264]
**Is your feature request related to a problem? Please describe.**
Add ability to specify the cluster in `data.nutanix_image` and `data.nutanix_subnet`. Currently, if you use Prism Central as an endpoint, and have the same image or network name on multiple clusters, you'll get a response similar to:
```terraform
Error: your query returned more than one result. Please use subnet_id argument instead
  on nutanix.tf line 45, in data "nutanix_subnet" "network":
  45: data "nutanix_subnet" "network" {
```

**Describe the solution you'd like**
Be able to specify the cluster, such that you can specify:
```terraform
data "nutanix_subnet" "network" {
  subnet_name  = "foo"
  cluster_uuid = var.my_cluster_uuid
}

data "nutanix_image" "image" {
  image_name   = "foo"
  cluster_uuid = var.my_cluster_uuid
}
```
While you can use the image and network UUIDs in the examples given above, the UUIDs aren't easy to get if your subnets were created outside of Terraform

**Comment by yga-ftp** [comment]
Hello @GNewbury1,
I face to the same issue and I don't find a solution. I see that you close your issue, so I think you find a workaround.
What was your solution ? 

Thanks in advance !

**Comment by IlyaVKulik** [comment]
Did you find a solution for this?

**Comment by yga-ftp** [comment]
Hi @IlyaVKulik, 
As a workaround, I create two zipmap. The first associates subnet UUID with their name. The second associates subnet UUID with cluster name. Then I filter and cross the two maps to get only the subnet UUID with the desired name that is in the desired cluster.

**Comment by IlyaVKulik** [comment]
@yga-ftp Thank you for the idea. I'm new in Terraform. Could you share any example?
Regards,
Ilya
