### ISSUE TITLE
Extend Provider to cover common Era operations via Era API

### ISSUE THREAD

**Issue by jlaunier** [nutanix/terraform-provider-nutanix#267]
Era Capabilities we are look to support from the provider:

1st Day tasks:
Provision Databases
Provision Database Servers

2nd Day tasks:
Backup/Recovery
Take a snapshot of a database
Restore a database 

Manage Clones
Create a Cloned Database
Refresh of a Cloned Database.

Patching
Apply new patches update to my database server

**Comment by abhimutant** [comment]
NDB feature is already released in v1.8.0
