### ISSUE TITLE
hard code (kind) to be appropriate kind for each resource

### ISSUE THREAD

**Issue by JonKohler** [nutanix/terraform-provider-nutanix#27]
Let's do this so it doesn't *need* a metadata group in the .tf definition file. We're going to make this implicit in a future API update, so hardcode should be fine.

We should do this for anything where the kind is 1:1, like this:

  cluster_reference = {
    kind = "cluster"
    uuid = "${data.nutanix_clusters.clusters.entities.0.metadata.uuid}"
  }

**Comment by marinsalinas** [comment]
The new reference for cluster will be removing cluster_reference to cluster_uuid like the following example (see bdc5046ae962033c89a1c7ffc9ce5381b96860de):

```hcl
resource "nutanix_virtual_machine" "vm" {

  name                 = "test-nutanix-vm-${count.index + 1}"
  description          = "testing vm"
  num_vcpus_per_socket = 1
  num_sockets          = 1
  memory_size_mib      = 2048
  cluster_uuid = "${data.nutanix_clusters.clusters.entities.0.metadata.uuid}" #new configuration

  nic_list = [{
    subnet_reference = {
      kind = "subnet"
      uuid = "${nutanix_subnet.sub.id}"
    }
  }]

  disk_list = [{
    data_source_reference = [{
      kind = "image"
      uuid = "${nutanix_image.test.id}"
    }]

    device_properties = [{
      device_type = "DISK"
    }]

    disk_size_mib = 5000
  }]
}
```

Other references would be changed like cluster reference.
