### ISSUE TITLE
Ability to add VMs to a protection domain

### ISSUE THREAD

**Issue by jantari** [nutanix/terraform-provider-nutanix#275]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
We require the ability to add newly created AHV VMs into a protection domain (for Veeam backup)

**Describe alternatives you've considered**
We've considered executing a `curl` command to call the Prism Element API (`https://prismElementNode:9440/PrismGateway/services/rest/v2.0/protection_domains/xxx/protect_vms`) from inside a null_ressource or similar, but that's not declarative, [wouldn't allow us to handle errors](https://github.com/hashicorp/terraform/issues/15469) and doesn't end up being recorded in the VMs terraform state.

**Additional context**
We are currently using Prism Central 2021.1.0.1 and AOS 5.15.5.1 LTS.

**Comment by premkarat** [comment]
We don't have plans to support v2 API

**Comment by jantari** [comment]
Right, which is why this critical functionality has to be added to the v3 API as soon as possible
