### ISSUE TITLE
Add support for new Karbon features

### ISSUE THREAD

**Issue by yannickstruyf3** [nutanix/terraform-provider-nutanix#290]
Add support for new Karbon features (upgrades/node pools/...) in the TF provider

**Comment by marinsalinas** [comment]
@yannickstruyf3 , can you describe which features need to be added to the provider?

**Comment by Fen0l** [comment]
Hi, I think it would be nice to add the ability to create multiples node pools directly from terraform (Karbon 2.3). As for now, only 1 worker_node_pool can be declared (worker_node_pool: attribute supports 1 item maximum, config has 2 declared).

If we create more Pools directly from Karbon UI, terraform want to re-create the cluster.

**Comment by yannickstruyf3** [comment]
Thanks for the feedback @Fen0l 

@marinsalinas 
Support for adding, removing node pools and managing the respective labels will be the primary focus.

**Comment by Chup4Chups** [comment]
Hi team,

Any update / ETA about this feature ?
We are stuck with terraform until this feature is implemented...

**Comment by Chup4Chups** [comment]
@yannickstruyf3 is it possible to include this one in the 1.5 ?

**Comment by Fen0l** [comment]
> Hi, I think it would be nice to add the ability to create multiples node pools directly from terraform (Karbon 2.3). As for now, only 1 worker_node_pool can be declared (worker_node_pool: attribute supports 1 item maximum, config has 2 declared).
> 
> If we create more Pools directly from Karbon UI, terraform want to re-create the cluster.


Hello Team,
Is there any update/ETA regarding this feature ? Thanks in advance

**Comment by Golgautier** [comment]
Hi Team,

I would like to know if anything is planned to add the update feature for k8s and node OS ?

Thank you

**Comment by abhimutant** [comment]
Hi, with v1.9.0 provider version we can only add worker nodepool in k8s cluster. 
With v1.9.0,  Node OS and K8s version cannot be updated as there are no public v3 APIs. @yannickstruyf3
