### ISSUE TITLE
Add a complete example of parameter nutanix_guest_tools

### ISSUE THREAD

**Issue by FlochonR** [nutanix/terraform-provider-nutanix#299]
Hello !!

I'm using the resource nutanix_virtual_machine and I would like to use the parameter "nutanix_guest_tools"
Unfortunately, I don't find well how can I configure it to have something that's working si if someone has an exemple to share I would be happy :)

Thanks,
FlochonR

**Comment by abhimutant** [comment]
Hi, we have added examples for nutanix_guest_tools. 
Refer: https://github.com/nutanix/terraform-provider-nutanix/tree/master/examples/virtual_machine_with_ngt_install .
