### ISSUE TITLE
VM creation fails when boot_type = LEGACY

### ISSUE THREAD

**Issue by brunobenchimol** [nutanix/terraform-provider-nutanix#304]
### Nutanix Cluster Information
AOS: 5.20 LTS
Prism Central: pc.2021.9

### Terraform Version
Terraform v1.0.10
on linux_amd64
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/nutanix/nutanix v1.2.1

### Affected Resource(s)
* nutanix_virtual_machine

### Terraform Configuration Files
```hcl
resource "nutanix_virtual_machine" "vm" {
  name                 = "vm-ntnx"
  count                 = 1
  cluster_uuid       = data.nutanix_cluster.cluster.id
  num_sockets     = 1
  memory_size_mib   = 2048

  boot_type = "LEGACY"

  disk_list {
    data_source_reference = {
      kind = "image"
      uuid = data.nutanix_image.image.id
    }
```

### Expected Behavior

VM creation with BIOS firmware.

### Actual Behavior

│ Error: error waiting for vm (b635f363-bde0-4ba1-aec2-22be78543d83) to create: error_detail: INTERNAL_ERROR: Internal Server Error., progress_message: create_vm
│ 
│   with nutanix_virtual_machine.vm[0],
│   on main.tf line 36, in resource "nutanix_virtual_machine" "vm":
│   36: resource "nutanix_virtual_machine" "vm" {

### Steps to Reproduce
1. `terraform apply`

### Important Factors

If you comment out boot_type it works properly. 
If you output boot_type after vm is created without boot_type set it outputs empty values:

```
output "boottype" {
  value = nutanix_virtual_machine.vm.boot_type
}
```
boot_type = [
  "",
]

It should show "LEGACY" (acorrding provider documentation) or "BIOS" (as shown on Prism UI).

**Comment by abhimutant** [comment]
Hi @brunobenchimol , 
1. when you setting boot_type, i would recommend to pass with boot_device_order_list . It's a requirement from create_vm . A disk_address, mac_address, boot device order must be specified for the non UEFI boot configuration . 
2. Output shows  empty values expected . If the value is not explicitly set, it falls back to default. when something is omitted from response, you can assume it takes on a default value.

**Comment by abhimutant** [comment]
Closing this issue. Feel free to reopen if issue persists.
