### ISSUE TITLE
Allow Subnet Datasources to filter based on PE ID

### ISSUE THREAD

**Issue by yannickstruyf3** [nutanix/terraform-provider-nutanix#308]
**Is your feature request related to a problem? Please describe.**
The terraform provider currently (v1.2.x) fails when the subnet data source is used to fetch a subnet with a non-unique name.

**Describe the solution you'd like**
We should provide the capability to (optionally) filter subnets based on PE ID

**Comment by shreevari** [comment]
@yannickstruyf3 Is this filter required on `Subnet` datasource or `Subnets` datasource?
