### ISSUE TITLE
Support defining categories_mapping for a VM

### ISSUE THREAD

**Issue by jantari** [nutanix/terraform-provider-nutanix#321]
**Is your feature request related to a problem? Please describe.**

We require the ability to set more than 1 category key and value for some VMs.

Currently the latest terraform provider 1.2.2 only supports defining:

```
categories {
  name = "a"
  value = "b"
}
```

on a VM which is immensely limiting.

**Describe the solution you'd like**
Being able to utilize the modern categories_mapping instead of the legacy categories so we can set multiple values for one key or just multiple keys in general. The API is described here: https://www.nutanix.dev/reference/prism_central/v3/api/vms/postvms

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by premkarat** [comment]
Please use multiple categories to pass a list of categories. Example below
 categories {
    name  = yyy
    value = xxx
  }
  categories {
    name  = aaa
    value = bbb
  }
  categories {
    name  = ccc
    value = ddd
  }

Please feel reopen if you feel its still unanswered

**Comment by jantari** [comment]
Hello, that does not work when I try to apply multiple values of the same category, e.g.:

```hcl
  categories {
    name  = "BackupJob"
    value = "VMBackup_Default"
  }

  categories {
    name  = "BackupJob"
    value = "VMSnapshot_4Daily"
  }
```

When this is done through the Prism Central Web GUI and I query the V3 API for the VM information I see it looks like this:

```json
    "categories": {
      "BackupJob": "AHVVMSnapshot_4Daily"
    },
    "categories_mapping": {
      "BackupJob": "VMBackup_Default VMSnapshot_4Daily"
    },
```

but when I plan the HCL shown above, terraform flip-flops the value of "categories" back and forth between "BackupJob: VMBackup_Default" and "BackupJob: VMSnapshot_4Daily" after every apply:

```console
Terraform will perform the following actions:
  # nutanix_virtual_machine.vmname[0] will be updated in-place
  ~ resource "nutanix_virtual_machine" "vmname" {
        id                                               = "86557160-51be-4de4-9863-30db2f3e5ee2"
        name                                             = "rz-app-zend"
        # (41 unchanged attributes hidden)
      - categories {
          - name  = "BackupJob" -> null
          - value = "VMSnapshot_4Daily" -> null
        }
      + categories {
          + name  = "BackupJob"
          + value = "VMBackup_Default"
        }
        # (6 unchanged blocks hidden)
    }
Plan: 0 to add, 1 to change, 0 to destroy.
```
