### ISSUE TITLE
Provider for darwin_arm64

### ISSUE THREAD

**Issue by d4vydm** [nutanix/terraform-provider-nutanix#331]
Request for a Nutanix terraform provider for darwin_arm64 architecture (Apple M1).

**Comment by simplydreamy0** [comment]
Agreed, I use an apple Silicon M1 Pro currently and to use this provider I have to start an amd64 VM with Lima, install terraform on it, mount a specific projects in the VM with read/write operations allowed and only then I can install the provider with `terraform init`. This is a bit painfull, considering the performances of Lima for amd64 VMs on arm64 are not that good.

Would it be possible to compile the provider for arm64 architectures in the Github Workflow and release it at the same time with the amd64 ? (I actually don't know if it works this way to release providers).

**Comment by premkarat** [comment]
This is already available here.
https://github.com/nutanix/terraform-provider-nutanix/releases/tag/v1.3.0.
Please feel free to reopen if you disagree.
