### ISSUE TITLE
[Foundation] Provision Image Nodes

### ISSUE THREAD

**Issue by siddharth-nutanix** [nutanix/terraform-provider-nutanix#354]
Nutanix provides deployment of nutanix cluster via Foundation. 

Add capability to deploy image nodes or clusters via terraform provider.

APIs: https://www.nutanix.dev/api_references/foundation/#/ZG9jOjQ1Mg-foundation-hub

**Comment by bhati-pradeep** [comment]
Released in `1.5.0-beta`
