### ISSUE TITLE
unable to spin vm with error "'api_version' is a required property"

### ISSUE THREAD

**Issue by vishwavijayverma** [nutanix/terraform-provider-nutanix#36]
**Describe the bug**
Terraform VM provisioning failing.

**Expected behavior**
terraform apply should able to create VM

**Logs**
2019/03/01 19:51:08 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* nutanix_virtual_machine.agentvm: error: {
  "api_version": "3.0",
  "code": 422,
  "message_list": [
    {
      "details": {
        "": [
          "'api_version' is a required property"
        ]
      },
      "message": "Request could not be processed.",
      "reason": "INVALID_REQUEST"
    }
  ],
  "state": "ERROR"
}
2019/03/01 19:51:08 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* nutanix_virtual_machine.agentvm: error: {
  "api_version": "3.0",
  "code": 422,
  "message_list": [
    {
      "details": {
        "": [
          "'api_version' is a required property"
        ]
      },
      "message": "Request could not be processed.",
      "reason": "INVALID_REQUEST"
    }
  ],
  "state": "ERROR"
}

**Versions (please complete the following information):**
 - OS that is executing Terraform Mac Darwin Kernel Version 17.4.0
 - Terraform
  0.11.11  
 - Nutanix Cluster (Prism Element / AOS)

AHV
Version Nutanix 20170830.94 
 - Nutanix Prism Central
 - Terraform provider version (using posted RC1? Compiling yourself? If so, from Develop or Master, and what commit id?
provider.nutanix: version = "~> 1.0"
**Additional context**
configuration

```hcl
provider "nutanix" {
  username = "xxx"
  password = "xxxx"
  endpoint = "xxxx"
  insecure = true
  port     = 9440
}


resource "nutanix_virtual_machine" "xxx" { 

# metadata { 
#  kind = "vm" 
#}
name = "agentvm"
description = "terraform test vm" 
num_vcpus_per_socket = 1 
num_sockets = 1 
memory_size_mib = 1024 
#power_state = "ON" 

cluster_reference = { 
kind = "cluster" 
uuid = "xxxxxxxx" } 

nic_list = [{ 
subnet_reference = { 
 kind = "subnet" 
 uuid = "xxxxxx" 
} 
}] 
disk_list = [{ 
data_source_reference = [{ 
kind = "image" 
#name = "Ubuntu-16.04.2.image" 
uuid = "xxxxx" }] 

device_properties = [
{ device_type = "DISK" }] 
disk_size_mib = 10000 }]
}

```

**Comment by vishwavijayverma** [comment]
Hi Nutanix team,  can you look into priority @jon@nutanix.com

**Comment by marinsalinas** [comment]
Hello @vishwavijayverma, which version of the binary are you using?

try with:
`terraform providers --version`

You can omit the provider part adding these environmental variables:
```
NUTANIX_USERNAME=<>
NUTANIX_PASSWORD=<>
NUTANIX_INSECURE=true
NUTANIX_ENDPOINT=<>
```

**Comment by briceo** [comment]
I am also getting this same error.  I have tried these configurations (note, that I have to changes the structure of `cluster_reference` depending on what version I am using):

```
Terraform v0.11.14
+ provider.nutanix v1.0.0
```

and 

```
Terraform v0.11.14
+ provider.nutanix v1.0.1
```

and I get the same result when running `terraform apply` (this is a brand new VM):
```
Error: Error applying plan:

1 error occurred:
        * nutanix_virtual_machine.boliver-test: 1 error occurred:
        * nutanix_virtual_machine.boliver-test: error: {
  "api_version": "3.0",
  "code": 422,
  "message_list": [
    {
      "details": {
        "": [
          "'api_version' is a required property"
        ]
      },
      "message": "Request could not be processed.",
      "reason": "INVALID_REQUEST"
    }
  ],
  "state": "ERROR"
}
```

**Comment by briceo** [comment]
For future readers, the reason I was getting the `api_version` error is because I had the wrong version of AOS/PC on our Nutanix system.  I was running 5.5.6, and I needed to be running 5.6.0 (or higher).

Once it was upgraded to 5.10.4.1 (the LTS at the time of this writing), the `api_version` error went away, and it worked as expected.
