### ISSUE TITLE
categories assignment on vm resource not working

### ISSUE THREAD

**Issue by JonKohler** [nutanix/terraform-provider-nutanix#40]
JKohlerVT-TBMBP:examples jon.kohler$ ./terraform plan

Error: nutanix_virtual_machine.demo-01-app: metadata (categories): '' expected type 'string', got unconvertible type '[]map[string]interface {}'

I got this when trying to use the commented code below. Looks like we have categories expecting a string, not an object (which it should be doing object, as category assignments are an object of key value pairs)

```
    metadata {
        kind = "vm"
        categories = "cat"
        # categories = {
        #     jondemo = "cat"
        # }
    }

**Comment by marinsalinas** [comment]
I already fixed it in #76
