### ISSUE TITLE
Allow project definiation by name and not just ID

### ISSUE THREAD

**Issue by FruityWelsh** [nutanix/terraform-provider-nutanix#406]
**Is your feature request related to a problem? Please describe.**
It would be a lot easier for users to be able to just define their project by the human readable name instead of needing the project-id.

**Describe alternatives you've considered**
I've considered trying to build a query in an upstream module, but I don't see how that would be done at this moment either.

**Comment by abhimutant** [comment]
Hey @FruityWelsh , can you point me to resource/data source this improvement is requested for ?

**Comment by abhimutant** [comment]
Closing this issue. Not sufficient information .
