### ISSUE TITLE
Change catagories from list to dictionary for more straightforward use

### ISSUE THREAD

**Issue by FruityWelsh** [nutanix/terraform-provider-nutanix#407]
Currently categories values are set in this method
```
  categories {
    name   = "Environment"
    value  = "Staging"
   }
 categories {
    name   = "AppTypet"
    value  = "DB"
   }
```
and result in a list object that contains dictionaries with the only keys name and value.
if catergories were a dictionary it could set simplier with:
```
categories {
  Enviroment = "Staging"
  AppType = "DB"
  ...
}
```

This also means now you can quickly check the output to ensure that a categories type is set and quickly check the value since it would just be:
``` .catergories.enviroment ``` instead of ```.categories[<unknown ranking in list>].value```

**Comment by bhati-pradeep** [comment]
Discussed with team and as schema will be closely related to APIs schema, decided to handle this while development of : https://github.com/nutanix/terraform-provider-nutanix/issues/482
Also suggested enhancement in this issue : https://github.com/nutanix/terraform-provider-nutanix/issues/483
