### ISSUE TITLE
Error when re-applying a plan

### ISSUE THREAD

**Issue by ryanhayesntnx** [nutanix/terraform-provider-nutanix#41]
**nutanix_virtual_machine.WD.0: internal error: cannot shut down the VM with UUID(a12dce4a-b1a4-4ad7-b581-1810aea2aa21): error updating Virtual Machine UUID(a12dce4a-b1a4-4ad7-b581-1810aea2aa21): error: {
  "api_version": "3.1",
  "code": 422,
  "message_list": [
    {
      "message": "Must specify NIC is_connected during update.",
      "reason": "INVALID_REQUEST"
    }
  ],
  "state": "ERROR"Describe the bug**

**Expected behavior**

**Logs**
If you've got any logs/outputs, attach them

**Versions (please complete the following information):**
 - OS that is executing Terraform
 - Terraform
 - Nutanix Cluster (Prism Element / AOS)
 - Nutanix Prism Central
 - Terraform provider version (using posted RC1? Compiling yourself? If so, from Develop or Master, and what commit id?

**Additional context**

**Comment by switchboardOp** [comment]
This is a duplicate of #33

**Comment by marinsalinas** [comment]
Closed by duplicate issue on #33
