### ISSUE TITLE
Make build possible

### ISSUE THREAD

**Issue by htj** [nutanix/terraform-provider-nutanix#41]
Hi

The current build fails due the private repo not being accessible:

htj@iridium:~$ go get github.com/nutanix/terraform-provider-nutanix
# cd .; git clone https://github.com/terraform-providers/terraform-provider-nutanix /Users/htj/go/src/github.com/terraform-providers/terraform-provider-nutanix
Cloning into '/Users/htj/go/src/github.com/terraform-providers/terraform-provider-nutanix'...
fatal: could not read Username for 'https://github.com': terminal prompts disabled
package github.com/terraform-providers/terraform-provider-nutanix/nutanix: exit status 128

If there is an alternative build process, please make it clear.

**Comment by JonKohler** [comment]
thanks @htj ! I'll have one of the guys look at this with priority so we can make sure we're providing the right guidance

**Comment by JonKohler** [comment]
hey @htj - Can you check out the latest build instructions in the readme now, and let us know if that works out for you?

**Comment by marinsalinas** [comment]
@htj the latest build instructions are in our `develop` branch.
here is:
https://github.com/nutanix/terraform-provider-nutanix/tree/develop

**Comment by htj** [comment]
Thanks.
I actually managed to build it later in the day, with instructions from another terraform plugin.
I'm sure this is all trivial stuff for people used to go, but I just haven't spend that much time with it.
