### ISSUE TITLE
Not able to upload image to a specific cluster

### ISSUE THREAD

**Issue by bhati-pradeep** [nutanix/terraform-provider-nutanix#428]
Problem Statement:
Image can be uploaded to a specific cluster incase of multi-cluster PC setup. Currently nutanix_image resource doesn't allow any attribute to perform such operation.

**Comment by Pencerval** [comment]
Thanks! Also, been able to specify a storage container will be helpful.

**Comment by bhati-pradeep** [comment]
@Pencerval I believe we can only upload image to the particular storage container by using PE. Terraform provider for nutanix uses PC APIs. cc: @siddharth-kulshrestha
