### ISSUE TITLE
Doc for Nutanix karbon_cluster_kubeConfig  pointing to deadlink in registry. 

### ISSUE THREAD

**Issue by abhimutant** [nutanix/terraform-provider-nutanix#429]
### Affected Resource(s)

* nutanix_karbon_cluster_kubeconfig

### Expected Behavior
The documentation present in https://registry.terraform.io/providers/nutanix/nutanix/latest/docs/data-sources/karbon_cluster_kubeconfig has at the bottom link for detailed information ([Get Nutanix Karbon Cluster KubeConfig](https://www.nutanix.dev/reference/karbon/api-reference/cluster/getk8sclusterkubeconfig/)) which is pointing to deadlink . 
### Actual Behavior
Detailed Information link should be working .

**Comment by abhimutant** [comment]
Fixed in #434

**Comment by bhati-pradeep** [comment]
Closing. Released in v1.5.0
