### ISSUE TITLE
Automate Foundation Central tests. 

### ISSUE THREAD

**Issue by abhimutant** [nutanix/terraform-provider-nutanix#438]
**Is your feature request related to a problem? Please describe.**
Automating the testcases for foundation Central data sources and resources for code coverage and avoiding regressions. Adding unit and acceptance  tests for foundation Central client code.

**Comment by abhimutant** [comment]
PR for issue: https://github.com/nutanix/terraform-provider-nutanix/pull/439

**Comment by bhati-pradeep** [comment]
Closing. Released in v`1.5.0`
