### ISSUE TITLE
cannot unmarshal string into GO struct field MessageResource.details of the type map [string]interface{}

### ISSUE THREAD

**Issue by ghost** [nutanix/terraform-provider-nutanix#44]
Getting the following error when setting up a vm on nutanix:
cannot unmarshal string into GO struct field MessageResource.details of the type map [string]interface{}

Please let me know if anyone has seen this error and what may be the cause

**Comment by marinsalinas** [comment]
@mkapooretg Can you share your configuration file and Prism Central version as well?

**Comment by titilambert** [comment]
On my side: 
```
Nutanix: Version 5.10.3
NCC Version: ncc-3.7.0.2
```

I just have


```
provider "nutanix" {
  username = "USERNAME"
  password = "PASSWORD"
  endpoint = "HOSTADDRESS"
  insecure = true
  port     = 9440
}

data "nutanix_clusters" "clusters" {
}
```

I tried:
* terraform v0.11.13 + terraform-nutanix 1.0
* terraform v0.11.11 + terraform-nutanix 1.0
* terraform v0.11.8 + terraform-nutanix 1.0
* terraform v0.11.13 + terraform-nutanix HEAD
* terraform v0.11.11 + terraform-nutanix HEAD
* terraform v0.11.8 + terraform-nutanix HEAD

Maybe it's because I don't have access to clusters ressources ?

**Comment by marinsalinas** [comment]
@mkapooretg : can I have the crash.log?

**Comment by rdobrynski** [comment]
I too seem to be experiencing this issue on terraform 0.11.14 and PC version 5.10.4
terraform plan works, but apply breaks.

**Comment by ghost** [comment]
Check the login information. Make sure that is correct.


Thanks,
Maneesh Kapoor | Essextec
Manager Professional Services
P: 929-371-3648<tel:929-371-3648> | C: 929-341-0431<tel:929-341-0431>
mkapoor@essextec.com<mailto:eherbst@essextec.com>
Website<http://www.essextec.com/> | LinkedIn <https://www.linkedin.com/company/essextec> | Twitter<https://twitter.com/essextec>
 [id:image001.png@01D50CDC.BCD63130]
Cloud | Cognitive | Cybersecurity

On Jun 5, 2019, at 6:09 PM, rdobrynski <notifications@github.com<mailto:notifications@github.com>> wrote:


I too seem to be experiencing this issue on terraform 0.11.14 and PC version 5.10.4
terraform plan works, but apply breaks.

**Comment by rdobrynski** [comment]
ahh.. silly domain suffix in username. Confirmed this is working with terraform 0.11.14 and PC version 5.10.4, thanks mkapoor

**Comment by scott-grimes** [comment]
Got hit by this: Nutanix returns a non-json object with response code 401 which cannot be unmarshaled by the CheckResponse method at https://github.com/terraform-providers/terraform-provider-nutanix/blob/8a3e566ff0a8520de9d7694e7c4315552c323cab/client/client.go#L263 

Reworked this with PR that throws an invalid credential error instead, which is more helpful I think #148
