### ISSUE TITLE
Unmarshalling error response invalid character 'I' looking for beginning of value for response body Internal Server Error since version 1.5

### ISSUE THREAD

**Issue by bartanthonissen** [nutanix/terraform-provider-nutanix#450]
Hi,

Our GitOps pipeline stopped working after the release of Nutanix provider 1.5:
- The source code that is failing didn't change
- No Nutanix upgrades have been done since the last successful run.
- Last working version is 1.4.1, which also doesn't seem to work anymore. (I tried pinning to that version)
- Ran our pipeline about 30 times, result: failed 28 times, two times it was actually able to so successfully run `Terraform plan`. The error we get is very random and not always on the same modules. e.g run 1: module devops_multi and training fail, run 2: build_assurance and consultants fail, ..etc

We have the current setup:

```
terraform {
    required_version = ">= 0.14" 

    ## Define the required version of the provider  
    required_providers {
        nutanix = {
        source  = "nutanix/nutanix"        
        version = "~> 1.2"  
        }
    }

    backend "local" {
        #path = "./terraform.tfstate"
    }
}

# configure provider authentication
provider "nutanix" {
    username = var.prism_user
    password = var.prism_password
    endpoint = var.prism_server
    port     = var.prism_port
    insecure = true
    wait_timeout = var.wait_timeout
```

Logs seem to indicate an internal server error response body:
[tasklog_10.log](https://github.com/nutanix/terraform-provider-nutanix/files/8669498/tasklog_10.log)

Nutanix version: 
<img width="248" alt="image" src="https://user-images.githubusercontent.com/36765901/167840762-0a965dfe-ba6a-4e4c-9057-f9e690b478bf.png">

Could you please assist on getting the Nutanix provider working again?, as we can't update our infrastructure right now.
Please let me know if this is the right place to solve the issue, our should open a Nutanix support ticket? (AKA not a provider issue, but a Nutanix infrastructure issue)

**Comment by bhati-pradeep** [comment]
Hi @bartanthonissen,
All resource and data sources seems to be failing as per the logs attached with `Internal Server Error` coming from PC API calls. Can you check once making an API call to the PC IP : 
```
API : https://<pc-ip>:9440/api/nutanix/v3/clusters/list
Payload: 
{
    "length":100
}
```
Also can you provide your pc version. Thanks

**Comment by bartanthonissen** [comment]
Hi, 

It seems that was indeed the issue. (API calls kept failing for some reason)
After restarting PRISM, the issue is solved.

Kind regards
Bart
