### ISSUE TITLE
Resizing disk identified in plan, but not actually done during apply

### ISSUE THREAD

**Issue by ksain-juul** [nutanix/terraform-provider-nutanix#463]
### Nutanix Cluster Information
Nutanix Cluster (Prism Element / AOS)
AHV VERSION NUTANIX 20170830.185

Nutanix Prism Central
(N/A - Dev instance, not attached to PRISM)

### Terraform Version

Terraform v1.1.9
on darwin_arm64
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/nutanix/nutanix v1.5.0
+ provider registry.terraform.io/strongdm/sdm v2.6.0

### Affected Resource(s)

* resource "nutanix_virtual_machine"
### Terraform Configuration Files

```hcl
resource "nutanix_virtual_machine" "vm1" {
  name         = "test1"
  
  cluster_uuid = data.nutanix_clusters.clusters.entities.0.metadata.uuid

  num_vcpus_per_socket = 1
  num_sockets          = 1
  memory_size_mib      = 2048

  disk_list {
    data_source_reference = {
      kind = "image"
      uuid = "1d5aa017-650f-458a-9ae3-501f1df34628"
    }    
    device_properties {
      disk_address = {
        device_index = 0
        adapter_type = "SCSI"
        disk_size_mib   = 100000
        disk_size_bytes = 104857600000
      }
      device_type = "DISK"
    }
  }
}
```
### Debug Output

https://gist.github.com/ksain-juul/b04e61503a400355fe5f5c0c87f0f954

### Panic Output
N/A
### Expected Behavior

Disk should be resized, and the change should be visible in the console.

### Actual Behavior

Disk is not resized.  It stays the same size as the original image size.  According to a documentation note below the disk_size_bytes section here - https://registry.terraform.io/providers/nutanix/nutanix/latest/docs/resources/virtual_machine#disk_size_bytes - it should be resized on subsequent apply's.  The included gist is from a 2nd apply as directed in the documentation.  The plan shows that it should be resized, but it does not resize.
The console Tasks section does not show any disk resize activity.

### Steps to Reproduce

1. `terraform apply`
### Important Factors
<!--- Are there anything atypical about your accounts that we should know?
For example if you are using a Prism Element or Prism Central -- >
​
### References
None found.

**Comment by abhimutant** [comment]
Hey @ksain-juul , You should provide disk_list in this format. 
 ```
   disk_list {
    data_source_reference = {
      kind = "image"
      uuid = nutanix_image.cirros-034-disk.id
    }    
    device_properties {
      disk_address = {
        device_index = 0
        adapter_type = "SCSI"
      }
      device_type = "DISK"
    }
      disk_size_mib   = 150000
      disk_size_bytes = 157286400000  
  }
```

**Comment by abhimutant** [comment]
Closing this issue. Please reopen if not working .
