### ISSUE TITLE
Resource "nutanix_subnet" fails when creating a managed IPAM network using a VLAN that overlaps with existing network

### ISSUE THREAD

**Issue by kingsleyck** [nutanix/terraform-provider-nutanix#543]
### Nutanix Cluster Information
 - Nutanix Cluster (Prism Element / AOS): 5.20.3
 - Nutanix Prism Central: pc.2022.6.0.1
### Terraform Version
Terraform v1.3.7
on windows_amd64
+ provider registry.terraform.io/nutanix/nutanix v1.7.1
### Affected Resource(s)
resource "nutanix_subnet"
### Terraform Configuration Files

```hcl
resource "nutanix_subnet" "next-iac-managed" {
  cluster_uuid = "<insertuuid>"

  name        = "next-iac-managed-example"
  vlan_id     = 0
  subnet_type = "VLAN"
  prefix_length = 20

  default_gateway_ip = "10.5.80.1"
  subnet_ip          = "10.5.80.0"

  dhcp_domain_name_server_list = ["8.8.8.8", "4.2.2.2"]
  dhcp_domain_search_list      = ["nutanix.com", "eng.nutanix.com"]
}
```
### Expected Behavior
If there is not an existing VLAN 0 network with Nutanix IPAM enabled, the subnet should be created successfully (which the GUI allows). In addition, the error message is too ambiguous to understand the root cause.
### Actual Behavior
```
Error: error waiting for subnet id (x) to create: error_detail: INTERNAL_ERROR: Subnet type provided is not supported, progress_message: create_subnet
```
The resource will only allow the subnet to be created when the VLAN is not 0. Changing the VLAN in the GUI post-create and updating the Terraform declaration functions as a workaround.
### Steps to Reproduce

1. Ensure a Network on VLAN 0 exists on the target cluster and is not configured for Nutanix IPAM.
2. `terraform apply`
### References

* #0000

**Comment by abhimutant** [comment]
PR: #562
