### ISSUE TITLE
Fix gocyclo issues reported by go report card

### ISSUE THREAD

**Issue by JonKohler** [nutanix/terraform-provider-nutanix#56]
Go report card is spotless as of the latest merge, with the exception of the gocyclo.

Perhaps @thetonymaster could help us sort this out?

gocyclo76%
Gocyclo calculates cyclomatic complexities of functions in Go source code. The cyclomatic complexity of a function is calculated according to the following rules: 1 is the base complexity of a function +1 for each 'if', 'for', 'case', '&&' or '||' Go Report Card warns on functions with cyclomatic complexity > 15.

terraform-provider-nutanix/nutanix/resource_nutanix_image.go
Line 114: warning: cyclomatic complexity 21 of function resourceNutanixImageRead() is high (> 15) (gocyclo)
Line 531: warning: cyclomatic complexity 17 of function getImageMetadaAttributes() is high (> 15) (gocyclo)
terraform-provider-nutanix/nutanix/resource_nutanix_virtual_machine.go
Line 976: warning: cyclomatic complexity 88 of function getVMResources() is high (> 15) (gocyclo)
Line 487: warning: cyclomatic complexity 78 of function resourceNutanixVirtualMachineUpdate() is high (> 15) (gocyclo)
Line 131: warning: cyclomatic complexity 61 of function resourceNutanixVirtualMachineRead() is high (> 15) (gocyclo)
Line 915: warning: cyclomatic complexity 16 of function getMetadaAttributes() is high (> 15) (gocyclo)
terraform-provider-nutanix/nutanix/data_source_nutanix_virtual_machine.go
Line 20: warning: cyclomatic complexity 76 of function dataSourceNutanixVirtualMachineRead() is high (> 15) (gocyclo)
terraform-provider-nutanix/nutanix/data_source_nutanix_subnet.go
Line 18: warning: cyclomatic complexity 53 of function dataSourceNutanixSubnetRead() is high (> 15) (gocyclo)
terraform-provider-nutanix/nutanix/resource_nutanix_subnet.go
Line 132: warning: cyclomatic complexity 52 of function resourceNutanixSubnetRead() is high (> 15) (gocyclo)
Line 345: warning: cyclomatic complexity 36 of function resourceNutanixSubnetUpdate() is high (> 15) (gocyclo)
Line 754: warning: cyclomatic complexity 28 of function setSubnetResources() is high (> 15) (gocyclo)
Line 579: warning: cyclomatic complexity 25 of function getSubnetResources() is high (> 15) (gocyclo)
Line 693: warning: cyclomatic complexity 16 of function getSubnetMetadaAttributes() is high (> 15) (gocyclo)
Line 29: warning: cyclomatic complexity 16 of function resourceNutanixSubnetCreate() is high (> 15) (gocyclo)
terraform-provider-nutanix/nutanix/data_source_nutanix_clusters.go
Line 22: warning: cyclomatic complexity 38 of function dataSourceNutanixClustersRead() is high (> 15) (gocyclo)
terraform-provider-nutanix/nutanix/data_source_nutanix_virtual_machines.go
Line 22: warning: cyclomatic complexity 36 of function dataSourceNutanixVirtualMachinesRead() is high (> 15) (gocyclo)
terraform-provider-nutanix/nutanix/data_source_nutanix_image.go
Line 19: warning: cyclomatic complexity 23 of function dataSourceNutanixImageRead() is high (> 15) (gocyclo)

**Comment by thetonymaster** [comment]
@JonKohler, let me go through a walkthrough of the code, and write somewhere some recommendations.

**Comment by JonKohler** [comment]
hey @thetonymaster - whats the status on this bit?

**Comment by mallochine** [comment]
shouldn't be too hard to fix. Just split out 10-line logic blocks into functions. Pretty standard refactoring on a big code base

**Comment by JonKohler** [comment]
Thanks @mallochine - @thetonymaster @marinsalinas @Crizstian - are you guys on this?

**Comment by thetonymaster** [comment]
We are currently working on the documentation,  missing resource and the bugs.

**Comment by JonKohler** [comment]
we've got a lot of loops, which I think is a bit inevitable with the way the code is currently. closing this out
