### ISSUE TITLE
availability_zone_reference not returning in nutanix_clusters

### ISSUE THREAD

**Issue by davemays** [nutanix/terraform-provider-nutanix#573]
### Nutanix Cluster Information

2022.9 and 6.6

### Affected Resource(s)

Terraform v1.4.2
on windows_amd64
+ provider registry.terraform.io/nutanix/nutanix v1.8.0

* nutanix_clusters

### Terraform Configuration Files

data "nutanix_clusters" "nutanix_clusters" {}

output "cluster" {
    value = data.nutanix_clusters.nutanix_clusters
}

### Expected Behavior

It should output "availability_zone_reference" in the output of the value.

### Actual Behavior

value is not in the output display.

### Steps to Reproduce

terraform plan

### Important Factors

* #0000

**Comment by abhimutant** [comment]
Hi @davemays , availability_zone_reference is not returned by clusters API.

**Comment by davemays** [comment]
It lists it in the API docs. Here https://registry.terraform.io/providers/nutanix/nutanix/latest/docs/data-sources/clusters.

Under Entities:

[availability_zone_reference](https://registry.terraform.io/providers/nutanix/nutanix/latest/docs/data-sources/clusters#availability_zone_reference): - The reference to a availability_zone.

**Comment by abhimutant** [comment]
You can verify the API response using the command: `export TF_LOG=TRACE`  .  It seems this field is added extra in API doc.

**Comment by abhimutant** [comment]
Closing this issue as no response from last 30 days.
