### ISSUE TITLE
How to configure IP address for  Nutanix Packer images? 

### ISSUE THREAD

**Issue by jlsilv159** [nutanix/terraform-provider-nutanix#576]
I created a Linux and Windows Image using the Nutanix Packer plugin. My Packer VM builders were configured to use DHCP for network connectivity. Now I need to deploy vm's to a server vlans where dhcp is not used (static ip's only). Is there any way to use my packer disk images and change the vm  nic settings from dhcp to static and configure the ip's from terraform?  Keep in mind that my terraform job will deploy them to a different vlan where dhcp is not available. The new vm will not be reachable until the ip's are changed. Remote-exec not an option unfortunately.  Thanks in advance.  :-)    https://github.com/nutanix-cloud-native/packer-plugin-nutanix

**Comment by tuxtof** [comment]
Hello @jlsilv159 

First question what is your Operating System ?

**Comment by jlsilv159** [comment]
Hi @tuxtof I am working with  Windows Server 2016/2019 and RHEL 7/8 servers. More specifically I wanted to know if there was any way to perform the vm customization with the Nutanix Terraform provider aside from sysprep\cloudinit solution. If not  any options using the v3 api?  Thanks

**Comment by tuxtof** [comment]
The only way to perform vm customization without network is to use sysprep\cloudinit solution.

But if your goal is to only configure a specific IP adress , best approach is to use a Nutanix Ipam network and specify the ip address in your terraform config, Address will be pass through the IPAM dhcp server 

+++
