### ISSUE TITLE
Include metadata example for data.nutanix_subnets

### ISSUE THREAD

**Issue by pipoe2h** [nutanix/terraform-provider-nutanix#590]
**Is your feature request related to a problem? Please describe.**
Include metadata example for data.nutanix_subnets on the same way there is for nutanix_clusters

**Describe the solution you'd like**
Show an example on using metadata on the data request to limit length or filtering

**Additional context**
Similar to screenshot but for nutanix_subnets
![image](https://user-images.githubusercontent.com/17649319/235857072-f5e6397b-3f14-497f-8d48-0cb3fc68f780.png)

**Comment by abhimutant** [comment]
Merged PR #643 .
