### ISSUE TITLE
Nutanix Karbon interaction

### ISSUE THREAD

**Issue by tuxtof** [nutanix/terraform-provider-nutanix#6]
Allow interact with Nutanix Karbon

new resources / data sources to implement

- nutanix_karbon_cluster

**Comment by alias-dev** [comment]
I put [this schema](https://gist.github.com/alias-dev/849291b6059a74d5c76edadd80dccb59) together as a start on this. Is the intention to add Karbon endpoints to the V3 API before it's GA or will it stay separate? I'm happy to put some time in if the API's stable enough to be worth investing it

**Comment by pierre-moire** [comment]
Hi, any news on this feature?
