### ISSUE TITLE
implement issue template

### ISSUE THREAD

**Issue by JonKohler** [nutanix/terraform-provider-nutanix#61]
Good source of inspiration from our buddies at google: https://github.com/terraform-providers/terraform-provider-google/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by marinsalinas** [comment]
You could add this template using this tutotial: https://help.github.com/articles/creating-issue-templates-for-your-repository/

**Comment by JonKohler** [comment]
https://github.com/nutanix/terraform-provider-nutanix/commit/325bc637b3168ad40d12780d6f31608e9056d191 done in develop, using to master
