### ISSUE TITLE
Resource "nutanix_karbon_cluster" , version should be properly set using karbon api response.

### ISSUE THREAD

**Issue by Abhishekism9450** [nutanix/terraform-provider-nutanix#610]
### Affected Resource(s)

* nutanix_karbon_cluster

### Expected Behavior
version should be set properly in karbon cluster resource. Incase, version is changed out of terraform (using UI) and if someone tries to match the version in hcl file. then resource should set the updated version in state file. 
### Actual Behavior
version doesn't update itself and causing the resource to destroy and recreate.

**Comment by abhimutant** [comment]
link to PR: #606
