### ISSUE TITLE
All "see detailed information" at the bottom of the doc pages are broken

### ISSUE THREAD

**Issue by pipoe2h** [nutanix/terraform-provider-nutanix#617]
Almost all the links at the bottom of the documentation for resources and data sources called `see detailed information` are broken. Examples:
- [See detailed information in Nutanix Host](https://registry.terraform.io/providers/nutanix/nutanix/latest/docs/data-sources/host).
- [See detailed information in NDB Clone](https://registry.terraform.io/providers/nutanix/nutanix/latest/docs/data-sources/ndb_clone).
- [See detailed information in Nutanix Project](https://registry.terraform.io/providers/nutanix/nutanix/latest/docs/resources/project).

**Comment by abhimutant** [comment]
Fixed. Relevant PR: #618
