### ISSUE TITLE
codify branching model for this project

### ISSUE THREAD

**Issue by JonKohler** [nutanix/terraform-provider-nutanix#62]
TLDR Summary: 
master is always "green" ... nothing gets committed to master without passing through develop first, with little to know exceptions
develop should also be "green" with little exceptions 
New feature work should go into feature branches and then be PR'd into develop

Should align with basic "sane" branching model here: https://nvie.com/posts/a-successful-git-branching-model/

Need to get this written down and documented, then put into practice, because otherwise we'll be over our skis on managing things at scale.

**Comment by marinsalinas** [comment]
You could se more details on: https://guides.github.com/introduction/flow/

Also here is a guide about how to protect branches in order to push directly on `master` : https://help.github.com/articles/configuring-protected-branches/

**Comment by JonKohler** [comment]
Way back when, I configured protected branching for master, and switched develop to the default branch. closing this out.
