### ISSUE TITLE
Updating gives error: Machine type must be set to Q35 for secure boot.

### ISSUE THREAD

**Issue by rmusyajucml** [nutanix/terraform-provider-nutanix#622]
### Nutanix Cluster Information
 - Nutanix Cluster (Prism Element / AOS) : 6.5.3.5
 - Nutanix Prism Central: pc.2023.1.0.1

### Terraform Version
Terraform v1.9.2 on linux_amd64

### Affected Resource(s)
nutanix_virtual_machine
​
### References
Same issue as 
https://github.com/nutanix/terraform-provider-nutanix/issues/494 

Request:
Need assistance importing PR in the latest version.

**Comment by abhimutant** [comment]
PR : #630

**Comment by abhimutant** [comment]
Merged in master!
