### ISSUE TITLE
Changing the VM name forces a reboot

### ISSUE THREAD

**Issue by ecov773** [nutanix/terraform-provider-nutanix#625]
### Nutanix Cluster Information
PC 2020.11 and earlier

### Terraform Version
0.13.x

### Affected Resource(s)
nutanix_virtual_machine

### Terraform Configuration Files
resource "nutanix_virtual_machine" "vm" {
  name                 = var.vm_name
  cluster_uuid         = data.nutanix_cluster.cluster.id
  num_vcpus_per_socket = "2"
  num_sockets          = "1"
  memory_size_mib      = 1024

  project_reference = {
    "kind" = "project",
    "name" = "my-project"
    "uuid" = "my-project-id"
  }
### Expected Behavior
VM should not be rebooted

### Actual Behavior
VM reboots when name is changed

### Steps to Reproduce
Create a VM
Change the VM name
VM reboots
### References
Here I found the same problem but when adding the VM to a project, I think the fix is easy and you just need to remove the hotPlugChange line for the name entry (https://github.com/nutanix/terraform-provider-nutanix/pull/232/files)

### Important Factors
#0000

**Comment by abhimutant** [comment]
Merged PR #626 .
