### ISSUE TITLE
Unable to filter subnet by cluster

### ISSUE THREAD

**Issue by jlsilv159** [nutanix/terraform-provider-nutanix#635]
### Affected Resource(s)

*data  "nutanix_subnet" "subnet"  your query returned more than one result. Please use subnet_id argument or use additional filter instead

unable to filter subnet by cluster  when building a vm and specifying a subnet name. We have the same subnet names configured on several clusters.  query returns all matching subnet names in prism central server. Need a clear example of how to filter results further if this is supported by cluster. 

when using data sources: 
data "nutanix_subnet" "test" {
  subnet_id = nutanix_subnet.test.id
}

data "nutanix_subnet" "test-name" {
  subnet_name = nutanix_subnet.test.name
}

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file.
```
### References

* #0000

**Comment by joeselway** [comment]
I am also having this issue - can you please advise what solution you found to mark as completed?
