### ISSUE TITLE
Project Support

### ISSUE THREAD

**Issue by bitrelay1** [nutanix/terraform-provider-nutanix#65]
Enterprise customer that would like to see project support and potentially even role support (as RBAC becomes more fine grain) in the Terraform provider.  This would give a powerful ability to properly manage (and template) projects properly, which currently can grow out of control without proper management/documentation because of a lack of visibility into each project consists of.

A simple workflow could be to create a project via a terraform provider with the for a development 'project'.  With support for the project to go into production that module is then used to create a production project.  Terraforms IAC module gives visability into what are in each project without messing with the Nutanix API to pull this information together.  It has become unwieldy to manage and remember what is in even as few as 25 project across a few clusters as my team as learned and this may help fix this big issue we have.

**Comment by LKS90** [comment]
+1
Ayy, would like to see the same thing. I am currently trying to automate and link together the project creation, was a bit baffled when I didn't find a single reference to projects. I can do the subnet management with terraform, but there is no projects?

The current plan is to just use the REST API itself, but it would be nice to get some timeframe so I at least know how robust my solution has to be :D.

**Comment by PacoDw** [comment]
Thank you so much for your request, I will start to develop the project resource :) and I will gave you news when I have something

**Comment by PacoDw** [comment]
Hello guys, good news the resource is done, now you can play with it at the issue #121

Please let me know if you find a bug, have another comment or concern, thank you so much

**Comment by bitrelay1** [comment]
Thank you!
