### ISSUE TITLE
Add datasource  type "hosts" for api/nutanix/v3/hosts endpoint

### ISSUE THREAD

**Issue by chandru-tkc** [nutanix/terraform-provider-nutanix#70]
**Is your feature request related to a problem? Please describe.**
api/nutanix/v3/hosts endpoint provides a lot of information about the host. For example if you have a cluster that has GPUs installed, v3/hosts will provide information about the device id, mode of operation of the GPU etc.., this information is needed if we want to create a virtual machine with gpu attached. 

**Describe the solution you'd like**
api/nutanix/v3/hosts endpoint provides a lot of information about the host. For example if you have a cluster that has GPUs installed, v3/hosts will provide information about the device id, mode of operation of the GPU etc.., this information is needed if we want to create a virtual machine with gpu attached. 

**Describe alternatives you've considered**
Current alternative is a python script that does api query and triggered the python script using data source external

**Comment by PacoDw** [comment]
Hello @chandru-tkc I added the data sources to retrieve the host data, you can check it out on the PR #116.

Let me know if you have another comment or concern, thanks
