### ISSUE TITLE
Update compatibility matrix for TF provider

### ISSUE THREAD

**Issue by chandru-tkc** [nutanix/terraform-provider-nutanix#71]
The current tf provider v1.0.1 will throw errors when it works with Prism Central version 5.9 due to difference between the API specs. An example is `is_connected` attribute is not available in Prism central 5.9 for nic card, so anyone using latest provider v1.0.1 with 5.9 will hit the following error,

```
 “api_version”: “3.1",
 “code”: 422,
 “message_list”: [
   {
     “details”: {
       “spec.resources.nic_list.0": [
         “Additional properties are not allowed (u’is_connected’ was unexpected)”
       ]
     },
     “message”: “Request could not be processed.“,
     “reason”: “INVALID_REQUEST”
   }
 ],
 “state”: “ERROR”
}
```

The readme on the github project just says it works with any PC 5.6.0+ which is not true in this case. Please provide a compatibility matrix for the provider and PC versions

**Comment by marinsalinas** [comment]
This issue was solved on #60.
