### ISSUE TITLE
Do not shutdown machine on certain changes

### ISSUE THREAD

**Issue by walkamongus** [nutanix/terraform-provider-nutanix#74]
**Is your feature request related to a problem? Please describe.**
Nutanix supports hot-plugging for things like CPU and memory, but currently changing this will result in a VM reboot/interruption.

**Describe the solution you'd like**
Certain changes to the VM (CPU and memory) should not initiate a shutdown/reboot.

**Describe alternatives you've considered**
I don't think there is an alternative in this particular case.

**Comment by walkamongus** [comment]
update shutdown code is at https://github.com/terraform-providers/terraform-provider-nutanix/blob/master/nutanix/resource_nutanix_virtual_machine.go#L984

**Comment by Jorge-Holgado** [comment]
Good afternoon,
I've done a little patch on the provider in my fork:
https://github.com/Jorge-Holgado/terraform-provider-nutanix

Options that will be hot-plug (always):
  * name
  * description
Options hot-plug just when increasing it:
  * num_vcpus_per_socket
  * num_sockets
  * memory_size_mib

You're right with the function location and the poweroff option, but there are some issues that I think I've solved. Give it a try and tell me if you have any issue.

**Comment by marinsalinas** [comment]
@Jorge-Holgado could you please open a PR with these changes?

**Comment by Jorge-Holgado** [comment]
@marinsalinas : Done!
