### ISSUE TITLE
Cannot specify target container when adding disks to a virtual machine resource

### ISSUE THREAD

**Issue by sbourdeaud** [nutanix/terraform-provider-nutanix#78]
Problem: When creating a virtual machine resource and specifying additional data disks, there is no way to specify the target storage container in disk_list, which means all data disk are added to the SelfServiceContainer by default, even if the VM itself was created in a different container.

Proposed solution: The API in Prism lets you specify a storage container when you add a disk to a VM.  This should be added to the disk_list attribute in the nuanix_virtual_machine resource specification.

**Comment by sbourdeaud** [comment]
After checking, it seems only API v2 has a way to specify a target container.  v3 does not offer that facility.  Looks like this will be added in 5.13 (https://jira.nutanix.com/browse/ENG-212697)

**Comment by moniquejank** [comment]
![70B30E84-C7E7-4CCA-B319-C3067F95C1E9](https://user-images.githubusercontent.com/56144595/71646199-8ee8ab80-2ce4-11ea-8400-f3585a370287.jpeg)
[Jankovic ](JankovicMonika)

**Comment by PacoDw** [comment]
Hello, @sbourdeaud I added the necessary changes to reference a container in the VM, you can check them in the PR #138.

Let me know if you have a comment or concern, thanks.
