### ISSUE TITLE
CPU and RAM change does not restart VM automatically

### ISSUE THREAD

**Issue by mritzmann** [nutanix/terraform-provider-nutanix#86]
**Describe the bug**
My guest system does not support Hotplug out of the box, so after CPU and RAM adjustment a restart is required. Terraform automatically restarts the affected VM when the size is reduced, but not when the size is increased. This feature was added in PR #75.

**Expected behavior**
Terraform should restart the affected VM. Or alternatively provide an option to configure this behavior.

**Logs**
I'll be happy to deliver more if necessary.

**Versions (please complete the following information):**
 - OS: Debian 8.11
 - Terraform: v0.11.14
 - Nutanix Cluster (Prism Element / AOS): Version 5.10.6 LTS
 - Nutanix Prism Central: 5.10.6
 - Terraform provider version: v1.0.2, installed with `provider "nutanix"`

**Additional context**
I created this issue as a bug, because the behavior has changed, without the possibility to keep the old behavior. So I can't enlarge VMs via Terraform anymore. Or is there a configuration option for it?

**Comment by mritzmann** [comment]
Build v1.0.2 without Hotplug:

```bash
docker run -it golang:1.12 /bin/bash

git checkout -b patch-revert 50863de314994937b0cf822ee63bf11e9c888ca8
git revert 7123f520971114e70accb598347bbbde871f602b
git revert 1ba8002fdbdb6202000c66496adebde451dda5c2
git revert 120d472d33c998e68b8e723a287b1e908babb4ab
git revert 1cc9c6db1124c9519aa1d8c1dff0affcde4f971c
git revert f61aa7364b0c15aa069e82846e5565771141a1db

go get -u github.com/golang/dep/cmd/dep

env CGO_ENABLED=0 GOOS=linux GOARCH=amd64 make build
```

**Comment by mritzmann** [comment]
From NTNX Case # 00669213:

> In that case the only workaround to Guest VMs that does not support hot add as of now would to use “power_state” attribute (https://www.terraform.io/docs/providers/nutanix/d/virtual_machine.html#power_state).
> 
> This involves a two step process though. First would be to update the Terraform file with increased resources to what you need and also add the "power_state" parameter with value "OFF" and apply the changes. This would update the resources and power off the VMs. 
> 
> The second step would be to update the same file or have a separate file with "power_state" set to "ON" which will power on the powered off VMs.
> I know that this is a longer process for now but I'm already in discussion with the developers and have agreed to add a parameter "reboot_on_update" which will be released soon that will help us to achieve what we need from just 1 terraform file without having to run multiple time.
> 
> As of now, we do not have an ETA on this but as soon as we have an update on this, I shall drop you an email.

**Comment by coderGo93** [comment]
Hello  @mritzmann, is this problem still happening on master? If so, can you share the config file without sensitive data so I can test and see what happens, please?

**Comment by coderGo93** [comment]
Hello @mritzmann , I just tested it seems it worked for me, I changed cpus/memory/sockets and it turns off then it turns on(Reboot) on master but I need your confirmation before this issue is already solved and closed.

**Comment by coderGo93** [comment]
Hello @mritzmann , I made [PR](https://github.com/terraform-providers/terraform-provider-nutanix/pull/136) with branch `fix-86/79` , a new parameter to force reboot for Cpus/memory changes, so if it's possible you can try it and see if it's ok, please?

**Comment by coderGo93** [comment]
Hello, I'm going to close because there are not responses from the issuer and it has been added a parameter for this case and merged to master.

**Comment by mritzmann** [comment]
Hi @coderGo93, thanks for your work. I tested it today with the 1.0 release. Seems to work fine!
