### ISSUE TITLE
Update Documentation for guest_customization_sysprep Attribute

### ISSUE THREAD

**Issue by 8c8jseKa** [nutanix/terraform-provider-nutanix#89]
Currently, the documentation (at the below link) only reflects the `PREPARED` option for the `install_type:` guest_customization_sysprep attribute. Please also reference that the `FRESH` option is available, as this can affect if an `unattend.xml` named-file is generated (`PREPARED`) or an `autounattend.xml` named-file is generated (`FRESH`).

[https://www.terraform.io/docs/providers/nutanix/r/virtual_machine.html](https://www.terraform.io/docs/providers/nutanix/r/virtual_machine.html)

**Comment by coderGo93** [comment]
Hello @8c8jseKa , I updated the doc with `FRESH` option as a valid value for `install_type` in this [PR](https://github.com/terraform-providers/terraform-provider-nutanix/pull/133)
