### ISSUE TITLE
Example config is not valid for power_state

### ISSUE THREAD

**Issue by JonKohler** [nutanix/terraform-provider-nutanix#9]
from https://github.com/nutanix/terraform-provider-nutanix/issues/216 @olljanat

> Describe the bug
> When I run command terraform validate with example config (and just build version of this plugin) it gives error:
> 
> Error: nutanix_virtual_machine.demo-01-web: "power_state": this field cannot be set
> If I remove this line from main.tf then validation works:
> 
>   power_state          = "ON"`

**Comment by marinsalinas** [comment]
Corrected in:
https://github.com/terraform-providers/terraform-provider-nutanix/commit/624b18e5927faf9da49c3ef2b5c515896e94929e
