### ISSUE TITLE
Incorporate gofmt simplify (gofmt -s)

### ISSUE THREAD

**Issue by JonKohler** [nutanix/terraform-provider-nutanix#91]
go report card keeps flagging non-simple code, which is a good thing.

Can we incorporate gofmt -s somewhere, perhaps in the makefile, or fmt checker script, to catch this before we land code? That would accelerate the process and close this quality gap from happening again.

**Comment by Crizstian** [comment]
This has been implemented in the Makefile

**Comment by JonKohler** [comment]
fixed
