### ISSUE TITLE
power_state trigger a syntax error.

### ISSUE THREAD

**Issue by jehutyy** [nutanix/terraform-provider-nutanix#94]
**Bug**
It seems that `power_state = "OFF"` trigger this error during `terraform plan -out plan:` 
```
Error: "power_state": this field cannot be set

  on foo.tf line 28, in resource "nutanix_virtual_machine" "foo_vm":
  28: resource "nutanix_virtual_machine" "foo_vm" {

```
**Expected behavior**
As I understand the provider reference, it should spawn vm in OFF/ON state.

**Versions**
I'm running a suse 15 sp1 with terraform 0.12.20. The nutanix provider comes from terraform init, it is v1.0.2_x4.

Beside power_state, I have no problem to create vms though.

**Comment by RagingPuppies** [comment]
Terraform v0.12.20
+ provider.nutanix v1.0.2

Error: "power_state": this field cannot be set

same here.

**Comment by marinsalinas** [comment]
This is related to #99 , see my comments in there.
