### ISSUE TITLE
How do I use an unattend.xml file?

### ISSUE THREAD

**Issue by RyanD0001** [nutanix/terraform-provider-nutanix#95]
Hi,

 when I try to use guest_customization_sysprep in my tf file i get 

**'Error: Incorrect attribute value type

  on Main-test.tf line 15, in resource "nutanix_virtual_machine" "TF-win19":
  15:   guest_customization_sysprep = "${base64encode(file("unattend.xml"))}"

Inappropriate value for attribute "guest_customization_sysprep": map of string
required.'**

What am I doing wrong?

this is my tf file:

resource "nutanix_virtual_machine" "TF-win19" {

  cluster_uuid = "00053994-c593-946e-6219-246e961bb700"
  name                 = "tf-testwin"
  description          = "created with terraform"
  num_vcpus_per_socket = 1
  num_sockets          = 1
  memory_size_mib      = 4096
  guest_customization_sysprep = "${base64encode(file("unattend.xml"))}"

  nic_list {
     # subnet_reference is saying, which VLAN/network do you want to attach here?
     subnet_uuid = "740da7c1-7278-403d-b362-b5204cd55d3a"
   }

  disk_list {

  data_source_reference = {
   kind = "image"
   uuid = "07c25fe9-2f3a-4ed3-97e7-b0d1268bc3ab"
    }

 
}

Thanks,

Ryan

**Comment by vCarbs** [comment]
Try adding this data block above the resource.
```
data "template_file" "init" {
  template = "${file("unattend.xml")}"
}
```
Then set the guest_customization_sysprep value to the below.
```
guest_customization_sysprep = {
          unattend_xml = "${base64encode("${element(data.template_file.init.*.rendered, count.index)}")}"
```

**Comment by RyanD0001** [comment]
Hi,

Do you have a fully working example that you can share?

Thanks,

Ryan

**Comment by vCarbs** [comment]
```
##################################################################################
# PROVIDERS
##################################################################################

provider "nutanix" {
  username     = "admin"
  password     = "mypassword"
  endpoint     = "10.1.1.1"
  insecure     = true
  port         = 9440
  wait_timeout = 10
}

##################################################################################
# DATA
##################################################################################

data "template_file" "cloud" {
  count    = 1
  template = "${file("sysprep.xml")}"
}

##################################################################################
# RESOURCES
##################################################################################

resource "nutanix_virtual_machine" "vm" {
  count                = 1
  name                 = "terraform_win"
  cluster_uuid         = "00053994-c593-946e-6219-246e961bb700"
  num_vcpus_per_socket = 2
  num_sockets          = 1
  memory_size_mib      = 4096
  nic_list {
    subnet_uuid = "740da7c1-7278-403d-b362-b5204cd55d3a"
  }
  disk_list {
    data_source_reference = {
      kind = "image"
      uuid = "07c25fe9-2f3a-4ed3-97e7-b0d1268bc3ab"
    }
  }
  disk_list {
    device_properties {
      disk_address = {
        device_index = 1
        adapter_type = "SCSI"
      }
      device_type = "DISK"
    }
    disk_size_mib = 40960
  }
  guest_customization_sysprep = {
    unattend_xml = "${base64encode("${element(data.template_file.cloud.*.rendered, count.index)}")}"
  }
}
```
